### ISSUE TITLE
Markdown image linking bug (Migration issue ?)

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#100]
https://beta.gmodstore.com/users/logoutphp

https://www.gmodstore.com/users/view/76561198001451981

notice the 

![](https://i.imgur.com/fH86hBA.png)

the markdown code i used was : `[![](https://pbs.twimg.com/media/DH-57S0XcAAhInb.jpg:large)](https://www.youtube.com/watch?v=GPxA6nasvQc)`

**Comment by ExtReMLapin** [comment]
Also happening here : 

https://beta.gmodstore.com/market/view/4858

![](https://i.imgur.com/RRIPB5q.png)

**Comment by Marcuzz** [comment]
I think the best solution here is to just go over manually and fix any broken links unfortunately. We convert markdown to HTML and shove it into quill and then it parses the HTML into a delta format in realtime. We have not ran a migration on all text at all as that would take an immense amount of time and there are no real html or markdown to delta quill converters

**Comment by ExtReMLapin** [comment]
Can we still make clickable image at least ? (I WOULD LOVE TO CHECK MYSELF BUT THE BETA IS CLOSED)

**Comment by Marcuzz** [comment]
@ExtReMLapin Yeah you can. Embed an image and then select it and use the link feature
