### ISSUE TITLE
Disabled scripts were not "ported"

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#103]
title

https://beta.gmodstore.com/market/view/2019 not working

https://www.gmodstore.com/scripts/view/2019 working

also the total sales are not counting the ones from the disabled scripts

**Comment by Marcuzz** [comment]
They were ported, but they are not in the database that is used on the beta site for some reason. Will try to import the database again later

**Comment by Marcuzz** [comment]
I was wrong, wasn't a database import issue, or a migration issue. It's just that "deleted_at" is filled and it has soft deletes enabled meaning it wouldn't show it.

https://beta.gmodstore.com/market/view/2019

Fixed
