### ISSUE TITLE
Access applications straight from job post.

### ISSUE THREAD

**Issue by OwjoTheGreat** [gmodstore/gmodstore-issues#104]
I mentioned this in #98 however it was a duplicate post as #97 was already posted.

It seems that there is no way to access your jobs applicants straight from the job post, but instead, need to go to your notifications and find a recent applicant and backtrack. Now, this could be because of issue #97 and it's hiding some button? Otherwise, it'd be a super useful feature for quick access.

**Comment by Marcuzz** [comment]
Fixed in next deployment
