### ISSUE TITLE
Forms don't save between user navigation

### ISSUE THREAD

**Issue by WilliamVenner** [gmodstore/gmodstore-issues#107]
Old behavior was that forms were "saved" and their content was retained when the user navigated away from the page.

**Comment by Marcuzz** [comment]
What forms in specific?

**Comment by WilliamVenner** [comment]
https://beta.gmodstore.com/market/create
and forum posts

**Comment by Marcuzz** [comment]
Because these are validated by js now

**Comment by WilliamVenner** [comment]
The issue is nothing to do with submitting the form.

**Comment by Marcuzz** [comment]
I don't really see why this is needed. Why would be navigating back and forth when you're filling out a form?

**Comment by ExtReMLapin** [comment]
There was another bug related to it, but i can't remember which one, gonna tell when beta is back for us

**Comment by WilliamVenner** [comment]
Because if you accidentally click off of a form while you're trying to fill
it out, you then instantly lose all of your work and typing just like that.
This was the behaviour of forms in V2.

**Comment by ExtReMLapin** [comment]
at least it was saving our shit with the `CRSF Token Mismatch` issue

**Comment by Marcuzz** [comment]
I don't really see a way for this to even be fixable. It's probably because some of our forms now use Vue and that behaviour is quite unfixable
