### ISSUE TITLE
increase background image max width

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#112]
![](https://i.imgur.com/mOiU13p.jpg)

not lookin good in 2560x1440

**Comment by WilliamVenner** [comment]
most people do not have a 2560x1440 monitor...

**Comment by Marcuzz** [comment]
This is a pretty tough one to fix actually. Our resizer is pretty bad at downscaling

**Comment by ExtReMLapin** [comment]
can't you just do something like width = 100% in the css ?

**Comment by Marcuzz** [comment]
That's not really the issue as that would look stretched. I'm talking about if we make the max width 2560 then the resizer will be really weird about 1920, and this issue will extend above 2560 as well as some people will have 4K screens too. It's a ballache

**Comment by WilliamVenner** [comment]
Here's what it looks like with `background-size: 100% 100%`, as you can see, the margins I created on my background are all over the place:

![](http://i.venner.io/chrome_2018-08-03_13-34-44.png)

Compared with

![](http://i.venner.io/chrome_2018-08-03_13-36-26.png)

**Comment by WilliamVenner** [comment]
Suggestion: keep background image sizing behaviour as-is, but give scripts the option to have their own background colors (default being gmodstore's blue), which would fill in the blanks.

**Comment by Marcuzz** [comment]
@WilliamVenner I don't think this would look good at all unfortunately
