### ISSUE TITLE
Addon background image blue tint is too powerful

### ISSUE THREAD

**Issue by WilliamVenner** [gmodstore/gmodstore-issues#113]
![](http://i.venner.io/chrome_2018-08-02_19-46-49.png)

**Comment by WilliamVenner** [comment]
imo, there shouldn't be a blue tint in the first place, if a content creator wants to add the blue tint then they can add it. fade to white is enough really.

**Comment by WilliamVenner** [comment]
Looks like this without the tint:

![](http://i.venner.io/chrome_2018-08-02_19-55-37.png)

**Comment by ExtReMLapin** [comment]
lapin agrees

**Comment by Marcuzz** [comment]
Not entirely sure what to do about this one. I really want the tint as that's the style of the website and I don't exactly trust people to make good looking backgrounds that fit in with the site at all

**Comment by WilliamVenner** [comment]
If you could make it a checkbox, that would be nice. Ultimately, it's up to content creators to make their backgrounds look nice, and if they don't look nice then that's their problem ;)

**Comment by WilliamVenner** [comment]
Maybe the feature could be restricted to popular addons only. Kind of like how YouTube's special branding features work.

**Comment by ExtReMLapin** [comment]
no discrimination billy pls

**Comment by WilliamVenner** [comment]
I didn't say best sellers, I said popular addons. So like 1,000 sales minimum or something. And that should branch off to the DLCs of it as well. Regardless, it's up to Marcuz.

**Comment by ExtReMLapin** [comment]
200 not 1000 lol

**Comment by ExtReMLapin** [comment]
riot if unhappy

**Comment by Marcuzz** [comment]
I'll look into this later, there are a lot of actual bugs to fix right now unfortunately

**Comment by Marcuzz** [comment]
Reduced from 0.35 to 0.15
