### ISSUE TITLE
"Purchased" and "Authors" not shown on a Discussion product page

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#116]
Not sure if it's normal or not, but I remember on an old discussion that an additional author should have something written like a "author" logo as the main creator on a comment he posted on a product he worked on
here you don't see the "author" badge on a comment in the discussion page, nor if the guy bought your script (except if you're going on his profile and shit) with the "purchased" thing

![](https://zupimages.net/up/18/31/9oja.jpg)

![](https://zupimages.net/up/18/31/pesn.jpg)

_Sorry about the f*cking pics, I'm not on my current computer and we don't care anyway_

**Comment by Marcuzz** [comment]
Yeah, this has not been added in v3 yet but should be

**Comment by Marcuzz** [comment]
Added
