### ISSUE TITLE
Monthly report generation doesn't work

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#117]
Tried to generate a report by clicking on the Download button at https://beta.gmodstore.com/dashboard/monthly-reports

ID695 - "This report is generating. Check back in a few minutes." message since more than 20 minutes and 'cause there is not so much sales I don't think it's normal

_**Sorry if it's only due to a huge load on your server**_

**Comment by Marcuzz** [comment]
Did you refresh?

**Comment by Marcuzz** [comment]
Nvm, fixed it
