### ISSUE TITLE
Scripts for sale statistic

### ISSUE THREAD

**Issue by JompeV** [gmodstore/gmodstore-issues#121]
On the main page of the old and new Gmodstore, it says how many active scripts there are for sale. However, the number on the old Gmodstore is ~880 while at the beta it is ~1150. I'm not sure if this is a bug or not but it seems kinda weird. My guess would be that the beta is counting disabled scripts as well.

**Comment by Marcuzz** [comment]
Will have to look into this, not sure why yet

**Comment by J0sh0nat0r** [comment]
Thanks for the report! This issue has been fixed in the next release.
