### ISSUE TITLE
Job I made doesn't appear in the job listings

### ISSUE THREAD

**Issue by Threebow** [gmodstore/gmodstore-issues#124]
Title

https://beta.gmodstore.com/jobmarket/jobs/26687
Not visible here: https://beta.gmodstore.com/jobmarket

**Comment by Threebow** [comment]
Ok so im blind, it appears just a lot lower than all the other jobs. Seems to be related to #126 
![](http://www.threebow.com/i/7f0c892d9dcb.png)

**Comment by Marcuzz** [comment]
Related to #126 and #99 for sure.

**Comment by Marcuzz** [comment]
Fixed
