### ISSUE TITLE
User list visual enchancements

### ISSUE THREAD

**Issue by Lunaversitay** [gmodstore/gmodstore-issues#127]
Should add either a faded red or wording on banned users such as everyones' favorite: 
![](http://i.avasdemon.rocks/firefox_2018-08-02_23-15-50.png)

Also should have a fallback for people w/ no avatars cause it causes this:
![](http://i.avasdemon.rocks/firefox_2018-08-02_23-16-33.png)

Finally, idk if its just me but I think the hover information for users should be increased, feels really slow having to hover for about 3-5 seconds.

**Comment by Marcuzz** [comment]
The hover is only set to 1000 ms

**Comment by Lunaversitay** [comment]
Really? It seemed super delayed when hovering over someone after you're already hovered over someone else.

**Comment by Marcuzz** [comment]
Added red text for banned
