### ISSUE TITLE
Wishlist isn't validated

### ISSUE THREAD

**Issue by Lunaversitay** [gmodstore/gmodstore-issues#128]
I put an addon I already own on my wishlist by just sending the post w/ my token

https://beta.gmodstore.com/users/76561198074425791/wishlist
https://beta.gmodstore.com/market/view/4748

**Comment by Marcuzz** [comment]
Not really an issue as even if you buy the addon it'll still stay on your wishlist. Should probably have a button to remove it but that's it

**Comment by J0sh0nat0r** [comment]
Thanks for the report! This issue has been fixed in the next release.
