### ISSUE TITLE
Discussions are still spammable

### ISSUE THREAD

**Issue by Lunaversitay** [gmodstore/gmodstore-issues#129]
Not that much of a big deal but people who usually can't wait a second double/quad post a shit ton by just clicking Reply. Should probably just add a front-end validator for that and call it done

https://beta.gmodstore.com/market/view/4748/discussion

![](http://i.avasdemon.rocks/firefox_2018-08-02_23-29-20.png)

(also idk if the timestamp is suppose to be broken but it is gamers)

**Comment by Marcuzz** [comment]
Timestamps is a different issue, we should probably add a back-end validation rule for this

**Comment by Marcuzz** [comment]
Added a 15 second cooldown
