### ISSUE TITLE
500 on this addon

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#131]
https://beta.gmodstore.com/market/view/4861

also :

https://beta.gmodstore.com/market/view/4854
https://beta.gmodstore.com/market/view/4852
https://beta.gmodstore.com/market/view/4835

**Comment by ExtReMLapin** [comment]
also it gives 500 instead of 404 https://beta.gmodstore.com/market/view/da

**Comment by Marcuzz** [comment]
Fixed, versions were null and the other bug is caused by an explicit binding throwing 500 instead of 404 because it's not an integer
