### ISSUE TITLE
Non-visible state of the approved/denied/pending scripts on the "Your addons" page

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#134]
The "Your addons" page now shows us our scripts denied, which was the problem I requested at https://github.com/gmodstore/gmodstore-issues/issues/118

But I think that the addons should be properly ordered alphabetically or at least by IDs, with a separation between the addons approved and those which are denied (or pending). Here, we have no way to see (except by clicking on the script) if the script is in a pending state or if it denied. I also don't see that my "Test page" addon is a denied one, and it is in the middle of my addons which has no sense at all.

![](http://image.noelshack.com/fichiers/2018/31/5/1533287391-addons.jpg)

**Comment by Marcuzz** [comment]
Fixed
