### ISSUE TITLE
Team overwiew doesn't show multiple rights of a user

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#135]
https://beta.gmodstore.com/dashboard/teams/2896/users

![](https://i.imgur.com/FizlBky.png)

![](https://i.imgur.com/ggbQpGX.png)

**Comment by Marcuzz** [comment]
Strange, could have sworn this worked previously

**Comment by Marcuzz** [comment]
Fixed, the issue was that when there's no permissions it doesn't say "none" - there's also a slight bug with caching I think
