### ISSUE TITLE
Error returned when you update support settings of a script

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#136]
When I tried to edit the support settings of a script, I firstly only wanted to check the "Enable the knowledge base" option. When I click on "Update", it returns me that "_The support message field must be a valid quill delta format_" but I don't think you are forced to put a support message.... Maybe you only want to enable the knowledge base and you should not be forced writing something?

Also, when I wrote a message for customers, it returns me that "_The support url format is invalid._" while my Support availability is set at " Supported through gmodstore support system (default)" so I don't see why I need any URL.

**Comment by Marcuzz** [comment]
validation field needs the `sometimes` and `nullable` flags

**Comment by Marcuzz** [comment]
Fixed
