### ISSUE TITLE
Profile is not saving 

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#138]
(diablos can't reproduce the bug)

https://www.youtube.com/watch?v=Wql3Y7lFBfY&feature=youtu.be

**Comment by ExtReMLapin** [comment]
but the video !!!!!

give yourself the rights to edit my profile and see it urself !!!


could be related to #100

**Comment by Marcuzz** [comment]
I just tried this, I can't replicate this even on your profile

**Comment by Marcuzz** [comment]
never mind, it only happens when you un-tick all boxes. got it

**Comment by Marcuzz** [comment]
Fixed

**Comment by ExtReMLapin** [comment]
why did u lock the beta!!!!!!!Le 3 août 2018 6:19 PM, Marcus <notifications@github.com> a écrit :I just tried this, I can't replicate this even on your profile

**Comment by Marcuzz** [comment]
Because we already have enough bugs to deal with for now

**Comment by ExtReMLapin** [comment]
github mail reply thing sucks
