### ISSUE TITLE
Ability to customize "featured" or "upgraded" scripts.

### ISSUE THREAD

**Issue by robertdrakedennis** [gmodstore/gmodstore-issues#142]
"restricted access to customize some of the colors on a script that's "upgraded"
on v3
like being able to change some panels and button colors
so we can have a bright / or dark mini-theme for the script theyre viewing
when it reaches that threshold you were talking about at one point
restricted as in you can just have a form that lets you change specific hex colors and that's it"

**Comment by HuntingVillager** [comment]
Nope.
