### ISSUE TITLE
Upgrade the dispute / chargeback message with extra resources

### ISSUE THREAD

**Issue by robertdrakedennis** [gmodstore/gmodstore-issues#144]
"
quick resources for users who chargeback or create a dispute
when you get a dispute message
you get the last time they downloaded, date or purchase, any relevant info like paypal email, ID's, all in a csv to give to paypal
and maybe like
quick actions
like report, revoke access, refund
"

**Comment by ExtReMLapin** [comment]
yeah i wanted to make some kind of shit like that, but idk if there is an API to automate the whole shit

**Comment by Marcuzz** [comment]
I think a PDF is more beneficial than a csv in this case
