### ISSUE TITLE
Dashboard tickets can be filtered by denied addons

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#145]
I am able to filter my tickets with a denied addon which is "Test page". Also the addon order is descending while it should be ascending.

![error1](https://user-images.githubusercontent.com/42046569/43687991-04f35094-98e1-11e8-9a8e-6ba9a33eb41a.jpg)

**Comment by Marcuzz** [comment]
Descending -> ascending is already fixed.

Filtering by denied addons is actually OK, don't really care about that to be fair

**Comment by DiablosCorp** [comment]
Then if you don't care I'm closing this.
