### ISSUE TITLE
adding a youtube video in the "add an image" field do this weird shit

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#147]
![](https://i.imgur.com/LYhIoax.png)

it shows this when editing 

![](https://i.imgur.com/lFi33uL.png)

but when posting : 

![](https://i.imgur.com/LlgTSre.png)

**Comment by Marcuzz** [comment]
Just don't add a youtube video in the image link I think. Not really worth validating
