### ISSUE TITLE
clicking on push notifications redirects to gmodstore, not the page of the notification or where it should go

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#148]
![](https://i.imgur.com/wmxS20s.png)

this, it redirects to gmodstore.com, not https://beta.gmodstore.com/notifications or https://beta.gmodstore.com/dashboard/tickets/102718

**Comment by Marcuzz** [comment]
I am aware of this but there's no fix I've come across yet as no matter what link I give it, the only place it wants to go is the home page. Doesn't listen to my input

**Comment by ExtReMLapin** [comment]
have you tried asking him nicely

**Comment by J0sh0nat0r** [comment]
Fixed in upcoming release.
