### ISSUE TITLE
Ticket attachment extensions

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#149]
As you can see at https://beta.gmodstore.com/help/tickets/view/102718 , I was able to put a .ini file while the allowed types should be "PNG, JPG, JPEG, TXT, LOG - Max File Size: 2 MiB". Not sure at if it's problem or not but since it's not an allowed type written, I only hope it's not a problem on the other extensions.

**Comment by Marcuzz** [comment]
This is because the mimetype of an .ini is the same as a txt file. Can you do any other file that isn't text based and not a part of the list?

**Comment by DiablosCorp** [comment]
Tried a lot of files, I can't upload them.
Right so it works, closing this issue.
