### ISSUE TITLE
Tickets and reports counter in the Help section + notification?

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#154]
It's written that there is "0" tickets and reports while I have 3 tickets opened. I thought that it was because I don't have any new notifications but when one of my tickets turned into "Awaiting agent", it doesn't change the counter anyway. Also didn't receive any notification when the agent answered.

![ticket_report](https://user-images.githubusercontent.com/42046569/43688258-b4cbaac6-98e5-11e8-9d8f-fbc43bb6f5a5.jpg)

**Comment by Marcuzz** [comment]
![image](https://user-images.githubusercontent.com/3168421/43688401-ee88c404-98e7-11e8-81d1-54e2cc305484.png)
