### ISSUE TITLE
Ticket descriptions syntax (for errors)

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#156]
The description syntax of the tickets have changed. However, I don't think they are good for errors. Here are the visuals of the current gmodstore website and the beta one.

Original:
![original](https://user-images.githubusercontent.com/42046569/43688865-50d47686-98f1-11e8-9888-2d39bee984a6.png)

New:
![new](https://user-images.githubusercontent.com/42046569/43688867-55e5bd1a-98f1-11e8-90e4-2d21e4458bde.png)

Since the **_** are considered as the beginning & the end of the italic syntax, they make things really weird. I don't know how you bypassed this on our current version, but the fact of not having this bypass on the new one could be a problem, I think so.

_Post Scriptum: don't tell me that my folders just have to be called another way, entities could have underscore and gmod_tool as well so all the content creators could receive weird errors_

**Comment by Marcuzz** [comment]
Only old tickets have this issue.
