### ISSUE TITLE
Error 500 for a new topic creation in a knowledge base category 

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#157]
I created my knowledge base for my script (ID3660), with a category called "DRM issue". I wanted to create a new topic, I put the topic name & body but when I click on "Create Topic" a 500 Internal Server Error appears.
Link at https://beta.gmodstore.com/help/addon/3660/drm-issue/create

**Comment by Marcuzz** [comment]
Fixed
