### ISSUE TITLE
Buyer rating completely wrong

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#158]
The buyer rating is entirely wrong.
If you go at https://beta.gmodstore.com/users/diablos, you'll see that I have
![new](https://user-images.githubusercontent.com/42046569/43689079-01fa180a-98f5-11e8-855b-0689eb5744e0.png)
while at https://www.gmodstore.com/users/view/76561197989318156, I have
![original](https://user-images.githubusercontent.com/42046569/43689078-fb08ea8a-98f4-11e8-9426-b25efb5a53c1.png)

This example also works with 76561198070943403, by example. Going to https://beta.gmodstore.com/users/76561198070943403 lets us see that the average doesn't go with the star color, since all stars have the same color while it's written that his average is fixed at 1.67.

**Also**, take a look at my screenshots. On the beta, the buyer rating is written as if it was calculated across 8 addons (since I have one denied script which is the test page). For real, I had and it was only across 7 scripts (those who are accepted but also those who have at least one review). It looks like that it only writes the number of addons you have posted, and not those who are accepted nor those who have at least one review.

**Comment by Marcuzz** [comment]
I might have to remove the buyer rating completely, and add it to team profiles once they are added. It just doesn't make much sense on a user profile anymore

**Comment by Marcuzz** [comment]
Removed it completely from here as it serves no purpose on user profiles anymore and would always be inaccurate here due to you technically not owning those sales, a team does.
