### ISSUE TITLE
Agreed budget negotiation notification takes you to a broken page.

### ISSUE THREAD

**Issue by OwjoTheGreat** [gmodstore/gmodstore-issues#159]
When you get a notification for someone agreeing to your budget (In this case, I was the job maker), clicking on the notification takes you to a broken page.

For example with [this job](https://beta.gmodstore.com/jobmarket/jobs/26678).
![](https://i.amowa.in/CDB028aT.png)
The notification shown above takes me to [this page](https://beta.gmodstore.com/jobmarket/jobs/26678/application/56934/budget/5), leaving a big red text error.

**Comment by Marcuzz** [comment]
Fixed for all new notifications in the next deployment
