### ISSUE TITLE
no price limit + another weird ass bug

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#161]
https://beta.gmodstore.com/market/view/2019

![](https://i.imgur.com/d1Y2v7U.png)

Notice the $1 ^^^^ 

notice the $0.56 vvvvv

![](https://i.imgur.com/jtAsdUz.png)

**Comment by ExtReMLapin** [comment]
also

![](https://i.imgur.com/ngSsXEI.png)

and 500 when setting it to 0.5

**Comment by Marcuzz** [comment]
Fixed in next deployment
