### ISSUE TITLE
video player is broken

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#162]
https://beta.gmodstore.com/market/view/3867 see here

**Comment by Marcuzz** [comment]
Works fine for me?

**Comment by ExtReMLapin** [comment]
![](https://i.imgur.com/rGr2n2G.png)

no error

**Comment by ExtReMLapin** [comment]
Internet explorer 6

**Comment by ExtReMLapin** [comment]
![](https://i.imgur.com/ULI4yET.png)

**Comment by Marcuzz** [comment]
![image](https://user-images.githubusercontent.com/3168421/43719697-af7487d8-998e-11e8-9987-6b20715c959d.png)

Works for me in both Chrome and Firefox, I'm not sure how it isn't showing up for you

**Comment by ExtReMLapin** [comment]
Got it working on firefox, still not working on chrome (even with all plugins disabled) weird

**Comment by handsomematt** [comment]
What does the DOM look like? Smiley face.
