### ISSUE TITLE
Error 500 when uploading a new version

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#163]
I tried to upload a new version at https://beta.gmodstore.com/dashboard/addons/4091/versions/create, I put version name and I choose the ZIP. When I click on "Upload" the 500 Internal Server Error is happening.

**Comment by ExtReMLapin** [comment]
Isn't the download server 100% dead anyway ?

**Comment by Marcuzz** [comment]
@ExtReMLapin Uploading a version is unrelated to the download server. This issue is definitely a bug

**Comment by Marcuzz** [comment]
Fixed in next deployment
