### ISSUE TITLE
Disabled co-created addon doesn't showup in the **profile** addons list

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#172]
https://beta.gmodstore.com/market/view/3867

doesn't showup on profile even if it showsup in dashboard list

![](https://i.imgur.com/twkBRRl.png)

**Comment by ExtReMLapin** [comment]
could be a feature, idk, non approved addons showsup so idk

**Comment by ExtReMLapin** [comment]
related to #172

**Comment by Marcuzz** [comment]
This doesn't seem to be an issue any more, right?

**Comment by J0sh0nat0r** [comment]
Seems to be fixed!
