### ISSUE TITLE
You can put the letter e in "numbers only" forms

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#174]
![](https://i.imgur.com/aag3nZS.png)

**Comment by Marcuzz** [comment]
But it still tells ya it's required? So what's the issue here exactly? I can't alter HTML behavior. It's only an issue if it let's you submit it and doesn't return an error.

**Comment by ExtReMLapin** [comment]
:(

**Comment by WilliamVenner** [comment]
`e` is used so that you can enter numbers in scientific notation, e.g. `1.234e15`

**Comment by ExtReMLapin** [comment]
ikr, still gay here

**Comment by Marcuzz** [comment]
you can put anything into the input field but it won't let you submit... idk why you thought `e` was extra special
