### ISSUE TITLE
500 error for missing forum pages

### ISSUE THREAD

**Issue by Havila199** [gmodstore/gmodstore-issues#176]
Tried to go to atlas' page on the beta and got a 500 error
https://www.gmodstore.com/community/threads/66-lets-give-this-a-shot-
https://beta.gmodstore.com/community/threads/66-lets-give-this-a-shot-

and doing https://beta.gmodstore.com/community/threads/66 just gives 404

**Comment by Marcuzz** [comment]
This is actually not a bug. That's a thread in the Refugee Camp (which no longer exists). All ban appeals were migrated to a new ban appeals area and deleted.
