### ISSUE TITLE
Missing "Discount Price" field

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#177]
The "Discount Price" value got imported from v2

![](https://i.imgur.com/KOaa7lP.png)

nothing here : 

![](https://i.imgur.com/DndrySo.png)

**Comment by J0sh0nat0r** [comment]
Sales are now managed from the team menu.

**Comment by ExtReMLapin** [comment]
Then you should add something that indicates it else people will keep asking the question
