### ISSUE TITLE
Script Review Reputation

### ISSUE THREAD

**Issue by IAMRichardT** [gmodstore/gmodstore-issues#18]
Would be a good idea to give [any] script collaborators reputation when a script is reviewed that they are part of. Currently, only the main developer of the script gets +1 after a review is placed by a customer.

Could possibly add another checkbox [This user receives reputation from reviews] or any collaborator that receives 50%+ share of the payment is automatically included.

**Comment by WilliamVenner** [comment]
This could be one of the options when adding a collaborator. You might not want them receiving extra reputation for various reasons.

**Comment by Marcuzz** [comment]
This is impossible with the way we currently calculate rep, we'd have to alter that in order to do this :s
