### ISSUE TITLE
"Last seen" and "Signed Up "and not correctly alligned

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#181]
![](https://i.imgur.com/b37fFao.png)

**Comment by Marcuzz** [comment]
What's wrong with the alignment, I don't see it :s

**Comment by ExtReMLapin** [comment]
Why is it right aligned and not in the center of the "frame"

**Comment by Marcuzz** [comment]
Because I couldn't make it center aligned properly while still aligning the icons properly :(

**Comment by J0sh0nat0r** [comment]
This issue has been fixed in the next release.
