### ISSUE TITLE
No antispam on the following things (Can be automated to spam)

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#192]
* [Script comments](https://beta.gmodstore.com/market/view/4858/discussion)

* [Thread creation](https://beta.gmodstore.com/community/boards/1)

Probably more but i can't see it rn because we don't have access to our own logs (Doesn't the GDPR requires you to show us our own logs ?)

**Comment by Marcuzz** [comment]
Created #200 - rate limiting should now work, closing
