### ISSUE TITLE
403 when trying to answer this thread

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#193]
https://beta.gmodstore.com/community/threads/5780/page/3

![](https://i.imgur.com/Op7pY2e.png)
![](https://i.imgur.com/yPVfcvq.png)

**Comment by Marcuzz** [comment]
@J0sh0nat0r I'm guessing this is because replying to a thread shares the same permission as posting a new one? We need a separate permission for replying to threads in a section. Can you look into this?

**Comment by J0sh0nat0r** [comment]
This issue has been resolved.
