### ISSUE TITLE
Push notifications are delayed/all comes at once

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#196]
![](https://i.imgur.com/qReHao1.png)

![](https://i.imgur.com/ILCVZvE.png)

Could be on my end, idk

**Comment by Marcuzz** [comment]
Is this after your browser has been closed for a while and you just open it?

**Comment by ExtReMLapin** [comment]
no, i didn't close it.

* Push notification created at 3am but not received since PC was off

* Was browsing beta branch from 10am to 1pm without getting any notification

* Later got 3 notification at the same time, two of them being super late



So yes, they are delayed

**Comment by ExtReMLapin** [comment]
I remember i started having this issue with scriptfodder then they just started ... not working anymore at all

**Comment by ExtReMLapin** [comment]
I don't have this issue anymore
