### ISSUE TITLE
Re-opening/closing the last ticket of a page should redirect to the next one

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#206]
Reopening : 

![](https://i.imgur.com/MKOpSfg.gif)

Closing : 

![](https://i.imgur.com/DWLVdFH.gif)

**Comment by ExtReMLapin** [comment]
don't tag it wontfix pls because this thing vv 

![](https://i.imgur.com/E1eQiNa.png)

also disappears

**Comment by J0sh0nat0r** [comment]
This issue has been fixed!
