### ISSUE TITLE
Can download my own revoked addon but can't download any other

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#207]
https://beta.gmodstore.com/users/WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW/purchases

![](https://i.imgur.com/NZ4hyhp.png)

* I can download my own addon that was revoked

![](https://i.imgur.com/LOoYX8t.png)
![](https://i.imgur.com/1ZuZsWg.png)

I can't download any other addons 

![](https://i.imgur.com/Kpqw3dg.png)

**Comment by ExtReMLapin** [comment]
And unrevoking my own addon makes the "Support" button disappear 


![](https://i.imgur.com/42opPjk.png)

**Comment by Marcuzz** [comment]
I'm gonna guess that the last one is because you are not really supposed to
have your own addon assigned, but the first part is strange

**Comment by Marcuzz** [comment]
Fixed in next release.
