### ISSUE TITLE
Support reps should see purchased scripts

### ISSUE THREAD

**Issue by Lunaversitay** [gmodstore/gmodstore-issues#21]
Support reps should be able to see purchased scripts from the Scripts they're added onto, right now I can only see people who bought my script instead of the scripts I do support for, for other creators, main reason why I'd like to see this is because someone asked for support on another script in the wrong script ticket, along with investigation shet.

**Comment by WilliamVenner** [comment]
Like this?

![](http://i.venner.io/chrome_2016-07-30_04-40-19.png)

**Comment by Lunaversitay** [comment]
yeee
