### ISSUE TITLE
"The description must only contain regular latin letters, numbers and symbols"

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#223]
![](https://i.imgur.com/Hl6r1Pe.png)

When editing the addon description

I'm just copy/pasting the stuff from here : https://www.gmodstore.com/scripts/view/4858 

# Emojis i guess

**Comment by CraigHulme** [comment]
remove any new lines (e.g. when you press enter).

**Comment by ExtReMLapin** [comment]
no

**Comment by CraigHulme** [comment]
works for me i guess ur frenchie mind is too small to understand

**Comment by ExtReMLapin** [comment]
you're claiming the newlines is blocking the description from being validated; are you stupid ?

I opened the issue when it was a private beta (accessible to CC only), marcuz since it fixed the issue (or someone else did), instead of shitposting here and opening issue with non-descriptive titles you should probably go back working on your addons

**Comment by CraigHulme** [comment]
toxic https://api.quackduck.xyz/u/2018-09-17_21-26-28.mp4

**Comment by ExtReMLapin** [comment]
I said the description, not the short description

**Comment by ExtReMLapin** [comment]
go away now
