### ISSUE TITLE
 teams/ID/addons isn't using the right banner

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#225]
![](https://i.imgur.com/DJiOEVu.png)

https://beta.gmodstore.com/teams/873/addons

it should be using  `920px x 260px` pic but it's using ` 280px x 120px.` pic

![](https://i.imgur.com/zoaV4hz.png)

**Comment by ExtReMLapin** [comment]
change the used pic of the size of box

**Comment by Marcuzz** [comment]
the 280px one is right above it, the ratio does not match. They are different images

**Comment by ExtReMLapin** [comment]
teams/873/addons ratio is ~ **3.15**  (378x120)

Listing pic ratio is ~**2.8** (280x120)

PAGE HEADER ratio is about **3.5** (920x260)

BIG HEADER ratio is ~**2.16** (900x415)


it's not fitting any of the uploadable pics, just resize it to any of the existing ratios

**Comment by Marcuzz** [comment]
![image](https://user-images.githubusercontent.com/3168421/45576213-8ca3d900-b876-11e8-955d-e29a3c20dd86.png)

**Comment by Marcuzz** [comment]
Thus, page header is the right image??
