### ISSUE TITLE
500 when trying to edit my addon 

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#229]
![](https://i.imgur.com/ObYEvuT.png)
![](https://i.imgur.com/CzEBRRk.png)

https://beta.gmodstore.com/dashboard/addons/4858/edit

I only tried to change the price from 0.05 to 5 (it was 0.05 because of matt and his `[Object object]` from yesterday)

**Comment by Marcuzz** [comment]
Fixed in next deployment
