### ISSUE TITLE
Can't update a denied script

### ISSUE THREAD

**Issue by ValfundeFR** [gmodstore/gmodstore-issues#237]
Hello, i can't update a denied script, it's saying " 403 No Permission You're not allowed to do that...", why ? :/

**Comment by Livaco** [comment]
As far as I can tell, the entire Dashboard is disabled.

**Comment by ValfundeFR** [comment]
It's a bit dumb

**Comment by Marcuzz** [comment]
This should now be fixed

**Comment by Marcuzz** [comment]
I forgot to mention, you need to re-submit the addon as it never added you to the team of the old one.
