### ISSUE TITLE
Editing existing knowledgebase topic creates 500 internal server error

### ISSUE THREAD

**Issue by DevulTj** [gmodstore/gmodstore-issues#245]
https://www.gmodstore.com/help/addon/5188/installation-guide/editing-or-creating-new-masks
![image](https://user-images.githubusercontent.com/22372616/45600782-32338580-b9fa-11e8-8d8f-a5cca2df23e2.png)

When I click edit on this, I retrieve this error:
![image](https://user-images.githubusercontent.com/22372616/45600786-437c9200-b9fa-11e8-9ab7-a245eb37cf01.png)

This renders the knowledgebase quite problematic to use when you're editing your existing topics.

**Comment by Marcuzz** [comment]
Fixed in next deployment
