### ISSUE TITLE
Description Character Limit

### ISSUE THREAD

**Issue by JompeV** [gmodstore/gmodstore-issues#252]
When changing my description it says that I can't use more than 10,000 characters. However, when I copy my description into a word-checker I only use ~5,000 words. I believe this is due to it counting the characters in image URLs as well. For people who want to style their descriptions, this can be really annoying.

**Comment by Marcuzz** [comment]
The issue here is that people like Lapin showcased that images can be abused infinitely if we don't count them in the word count. We'll just have to up the limit as Matt said

**Comment by Marcuzz** [comment]
Upping limit to 25,000 in next deployment
