### ISSUE TITLE
Weird sale number discrepancy

### ISSUE THREAD

**Issue by Threebow** [gmodstore/gmodstore-issues#256]
Script dashboard here: https://www.gmodstore.com/dashboard/addons/5555
Shows the all time total sales at 150

But the addon page itself shows purchases at 149: https://www.gmodstore.com/market/view/5555

**Comment by handsomematt** [comment]
I'm pretty sure this it to do with caching as they're equal now.

**Comment by Marcuzz** [comment]
I'm gonna mark this as fixed for now
