### ISSUE TITLE
Featured addons and popular ones should be the home page of gmodstore and "Marketplace" should not be a drop down menu

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#259]
In my opinion the Downdown menu here isn't right

![](https://i.imgur.com/rpBlHsD.png)

Two buttons are basically doing (almost) the same thing, clicking on "marketplace" should directly redirect [here](https://www.gmodstore.com/market/browse)

To see the featured and popular addons we should be only clicking the gmodstore logo, because it takes too much click to see the last released addons.

TL;DR : 

Clicking on marketplace should not open a drop down menu but directly redirect [here](https://www.gmodstore.com/market/browse)

**Comment by Threebow** [comment]
Gotta agree with you, I really don't see a need for a dropdown there to begin with.

**Comment by DrPepperGaming** [comment]
Its just annoying tbh

**Comment by Marcuzz** [comment]
Fixed in next deployment
