### ISSUE TITLE
Content Curator: Cannot view addon submissions

### ISSUE THREAD

**Issue by IAMRichardT** [gmodstore/gmodstore-issues#263]
Viewing newly submitted addons as a moderator works, however, after viewing the initial creation post; clicking "View Addon" returns a "403 No permission" error; so we cannot check new addons.

**Comment by Marcuzz** [comment]
This seems to work when I'm impersonating your user. Can you view https://www.gmodstore.com/moderator/submissions/106560 ? if so, can you try the other one too and see if it's that one you can't view?

**Comment by Marcuzz** [comment]
Fixed, was literally just missing a permission josh added
