### ISSUE TITLE
Weird algorithm for popular addons

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#270]
I don't see why the viewcount is checked in the algorithm because it doesn't mean anything.

https://www.gmodstore.com/market/view/4801 is younger and got more sales than https://www.gmodstore.com/market/view/5551 but isn't "popular"

https://www.gmodstore.com/market/view/5555 again got even more sales but isn't "featured" in the popular list

**Comment by ExtReMLapin** [comment]
More data : https://www.gmodstore.com/market/view/922

lmao this fucking script

**Comment by ExtReMLapin** [comment]
It seems to be working much better now, maybe it needed more data

**Comment by Marcuzz** [comment]
It definitely needed more data
