### ISSUE TITLE
disable stupid american 12h system

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#275]
american 12h system is stupid

disable it please

or at least let us use the superior non-murican 24h system

**Comment by ExtReMLapin** [comment]
![](https://i.imgur.com/YGP24CQ.png)

**Comment by handsomematt** [comment]
Will add a time display setting

**Comment by Marcuzz** [comment]
Using 24 hour format now, setting will be added later
