### ISSUE TITLE
"You don't have access to view statistics for this addon" while I'm the main author of it

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#277]
As the title said by itself, I can't view the statistics of my own addons while I'm the main author of the team:
![img](https://user-images.githubusercontent.com/42046569/45620922-bf202280-ba7e-11e8-8d60-876100e2d9b0.png)

Scripts affected are 3274 & 3660, which are those who have the TeamID3017 (with a cocreator).

Thanks.

**Comment by Marcuzz** [comment]
Fixed in next deployment (in 10 minutes ish)
