### ISSUE TITLE
v2 API is not working

### ISSUE THREAD

**Issue by WilliamVenner** [gmodstore/gmodstore-issues#278]
Request: `GET https://www.gmodstore.com/api/scripts/versions/1599?api_key=XXXXXXXXXX`
Response:
```json
{
    "message": "Server Error"
}
```

Request: `GET https://www.gmodstore.com/api/users/info/76561198040894045?api_key=XXXXXXXXXX`
Response:
```json
{
    "message": ""
}
```

**Comment by J0sh0nat0r** [comment]
Fixed.
