### ISSUE TITLE
Addon list isn't properly ordered

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#279]
The addon list at https://www.gmodstore.com/dashboard/addons has no sense at all, the order isn't by ID nor by name (even if make an order by name is useless) so I don't understand how it was made but it's weird anyway.

![img2](https://user-images.githubusercontent.com/42046569/45621648-5ab29280-ba81-11e8-8628-2bd0fc7450ff.png)

Thanks.

**Comment by Marcuzz** [comment]
Ordered by ID ascending in next deployment
