### ISSUE TITLE
All time earnings / Monthly Earnings statistics calculated wrong.

### ISSUE THREAD

**Issue by TeeJay007** [gmodstore/gmodstore-issues#280]
![image](https://user-images.githubusercontent.com/17435461/45623489-2f836f80-ba90-11e8-8995-fa26ce6437f7.png)
Surely I didn't made 1mil and 11k in a month.

**Comment by Marcuzz** [comment]
This is no longer an issue for me, it was fixed a few hours ago. Are you sure it's still like that for you?

**Comment by TeeJay007** [comment]
Hey, it just somehow fixed it self sorry for bothering.
