### ISSUE TITLE
Content Curator: Job Moderation

### ISSUE THREAD

**Issue by IAMRichardT** [gmodstore/gmodstore-issues#285]
Issue 1 
When reviewing a reported job, content curator does not have any visible tools to close/delete job reported if action is deemed necessary. We can only mark the initial report as "Solved".

_We do have the edit button, however, it only allows us to edit the title, description, and various other details about the job_

Issue 2 
When reviewing a job, Moderator gets 403 permission error when clicking 'View Applications'

**Comment by Marcuzz** [comment]
I have now made all of this way more clear and fixed it in the next deployment
