### ISSUE TITLE
we can't publish

### ISSUE THREAD

**Issue by enzio53** [gmodstore/gmodstore-issues#286]
we can not publish new addons, we have a 500 error

**Comment by ExtReMLapin** [comment]
u can't code anyway

**Comment by aanndrewh** [comment]
lmao rip.
But I can so pls fix @Marcuzz :))

**Comment by Marcuzz** [comment]
When is the last time any of you tried to submit an addon?

**Comment by enzio53** [comment]
this morning personally

**Comment by Marcuzz** [comment]
Can one of you try to submit an addon again and submit the error message when a 500 screen appears and tell me the event id you're given?

**Comment by enzio53** [comment]
> Can one of you try to submit an addon again and submit the error message when a 500 screen appears and tell me the event id you're given?

Event ID: 4e0f249136e24fbe819c9a4c30184ac4

**Comment by Marcuzz** [comment]
Thank you very much. Try again now :)

**Comment by enzio53** [comment]
> Thank you very much. Try again now :)

new bug after i'm redirect and i have "403 No Permission"

**Comment by Marcuzz** [comment]
okay. I will debug this

**Comment by enzio53** [comment]
I am redirected to paypal (normal?)

**Comment by Marcuzz** [comment]
It is here:

https://www.gmodstore.com/dashboard/addons

Once you are done editing it you can hit the "Submit for approval" link in your addon dashboard to submit it for approval.

**Comment by enzio53** [comment]
alright, thank you 👍
