### ISSUE TITLE
No longer "Recently Updated"

### ISSUE THREAD

**Issue by HavannaPC** [gmodstore/gmodstore-issues#287]
We can't sort anymore by "Recently Updated" in the Marketplace

**Comment by ExtReMLapin** [comment]
editing the description was a way to push the addon at the top of the list

**Comment by HavannaPC** [comment]
So just activate this feature when there is an update of the file, not the description

**Comment by ExtReMLapin** [comment]
ur hired

**Comment by HavannaPC** [comment]
I begin when ? :)
