### ISSUE TITLE
Ticket reply notifications don't get added

### ISSUE THREAD

**Issue by TrixterTheTux** [gmodstore/gmodstore-issues#289]
Title says it all, I've got them enabled in settings.

**Comment by ExtReMLapin** [comment]
Also does it with site tickets

**Comment by Marcuzz** [comment]
Can you send me a link to a ticket that has not given you a notification please?

**Comment by TrixterTheTux** [comment]
Any ticket since the update.
https://www.gmodstore.com/dashboard/tickets/106849
https://www.gmodstore.com/dashboard/tickets/106563

**Comment by Marcuzz** [comment]
Okay. I've identified the issue. It's not inserted users to the collaborators table upon creation of a ticket or response

**Comment by Marcuzz** [comment]
This is fixed in the next deployment (only after you've replied again)
