### ISSUE TITLE
500 on https://www.gmodstore.com/market/view/UID/reviews

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#291]
https://www.gmodstore.com/market/view/324/reviews
https://www.gmodstore.com/market/view/4858/reviews

**Comment by Marcuzz** [comment]
Can you even get to these links normally or did you manually type them in?

**Comment by ExtReMLapin** [comment]
they are the v2 links for reviews

**Comment by Marcuzz** [comment]
It's weird that they throw 500s, but they should no longer be navigated to manually like that as they are now basically APIs for Vue

**Comment by ExtReMLapin** [comment]
you can fix it with #300 if you just remove the page
