### ISSUE TITLE
All Job applicant proposed budgets set to $12 + smaller bugs

### ISSUE THREAD

**Issue by UltraTechX** [gmodstore/gmodstore-issues#293]
Since V3 of the site was put out I have noticed that all 3 of my active jobs have the applicant's bids all set to $12, although all 3 of them have bid amounts greater than that.

[Custom Microphone Model](https://www.gmodstore.com/jobmarket/jobs/27746)

Budget: $15

What ﻿﻿Old Bill﻿﻿ proposed in his original application (that I accepted): $20

What he now "proposes": $12

Screenshot:
https://i.imgur.com/HEBlAWW.png

-------------------------------------------------------------------------------------------------------------------------------------------------------

[Custom Intercom Entity](https://www.gmodstore.com/jobmarket/jobs/27737)

Budget: $30

What ﻿﻿Alabama﻿﻿ proposed in his original application (that I accepted): $30

What he now "proposes": $12

Screenshot:
https://i.imgur.com/ZmEiYuo.png

-------------------------------------------------------------------------------------------------------------------------------------------------------

[Map Optimization](https://www.gmodstore.com/jobmarket/jobs/27736)

Budget: $50

What ﻿﻿{I-M}Taz﻿﻿ proposed in his original application (that I accepted): $50

What he now "proposes": $12

Screenshot:
https://i.imgur.com/NnkgnpV.png

-------------------------------------------------------------------------------------------------------------------------------------------------------

It wants me to "confirm budget" on applications that now have completely screwed up prices, so I can't confirm until they are set back to their original proposed budgets set by the applicants (that I once again already accepted before the V3 update). Hopefully this is fixed quickly.

On a side note, the two buttons at the top, "view on dashboard" and "edit" give me a "403 no permission" error. Also some of those "progress bars" on the main job page seem to be off. Example image below.

https://i.imgur.com/8Ig26K8.png

Image above should be "In Progress". Anyways, that is all the issues I am having so far, and would love to hear back about them. 

Much Appreciated,
 - Ultra (Fat Gay)

**Comment by UltraTechX** [comment]
As a side note, one of the jobs was already paid and we exchanged then files and such before V3 came out, so we we're gonna turn off the seller protection and just mark it as done. The only problem is, the "edit job" button results in a "403 no permission" error.

**Comment by Marcuzz** [comment]
All previous job applications have their budget set to $12 for some reason. I'll fix edit job now though as we need more time to restore job application bids

**Comment by UltraTechX** [comment]
> All previous job applications have their budget set to $12 for some reason. I'll fix edit job now though as we need more time to restore job application bids

Alright, thank you for clarifying. If I have already payed the guy the requested amount and got what I paid for from the applicant, can I just "confirm" the incorrect budget so the applicant and I can mark the job as finished?

**Comment by Marcuzz** [comment]
In the negotiation stage you can confirm the correct budget, and mark the job as finished/paid yes

**Comment by Marcuzz** [comment]
You can now edit the job again

**Comment by Marcuzz** [comment]
For the other part of this bug I'm going to go ahead and update the bid of all applications to the same as the budget of the job, as there's no way for me to restore the old values at this point. Any invalid budget can be re-negotiated in the negotiation stage anyway
