### ISSUE TITLE
Unable to unzip any files without lua being deleted.

### ISSUE THREAD

**Issue by UnicornJesus** [gmodstore/gmodstore-issues#295]
I have bought and downloaded the zip files for multiple addons but when i open them i can see the lua in it, if i attempt to open it i get an error, if i extract the file it gives me an error and will only extract the directories and delete the lua.

**Comment by kanalumaddela** [comment]
unzip using 7zip

**Comment by handsomematt** [comment]
@UnicornJesus is there a specific addon that does this?

**Comment by handsomematt** [comment]
Should be fixed in next deployment, we'll see.
