### ISSUE TITLE
Support Settings - Message to Customers field must not be empty

### ISSUE THREAD

**Issue by BOTDan** [gmodstore/gmodstore-issues#296]
Upon updating the Support Settings tab of an addon, the Message for Customers entry returns this error when left blank:
`The support message must not be empty`
However, underneath, the helper text reads:
`If this is blank it simply won't show on the ticket page. Max 200 characters`
Meaning we have to add a message to customers if we want to update out support settings.

**Comment by Marcuzz** [comment]
Fixed in next deployment
