### ISSUE TITLE
Problems while connecting with Steam

### ISSUE THREAD

**Issue by Gabyfle** [gmodstore/gmodstore-issues#298]
After logging in with Steam, on the home page I don't see my profile.
![home](https://user-images.githubusercontent.com/18049206/45641997-4ab5a580-bab7-11e8-8ec6-c51c6b022e8b.png)
But on the other pages, I see myself connected.
![addons](https://user-images.githubusercontent.com/18049206/45642027-5d2fdf00-bab7-11e8-9790-b7a32b62fb50.png)

**Comment by Gabyfle** [comment]
This seems to happen only when you first connect to the site with your browser. The bug fixes itself when you navigate through the settings pages, but I'll try to find out where exactly.

**Comment by ExtReMLapin** [comment]
had this issue, just pressed shift-f5 to fix it

**Comment by kanalumaddela** [comment]
p sure this a client side issue with caching, tried logging out/back in, nothing happened. tried incognito, everything was fine

**Comment by Gabyfle** [comment]
@kanalumaddela I agree with you because when I refresh the page, ignoring the cache, everything is correct.

**Comment by handsomematt** [comment]
ah this is fixed now, were caching issues on CloudFlare
