### ISSUE TITLE
Hyperlink user accounts in "latest posts"

### ISSUE THREAD

**Issue by CraigHulme** [gmodstore/gmodstore-issues#299]
you see how they arent hyperlinked here
https://api.quackduck.xyz/u/chrome_2018-09-17_19-45-30.png

but they are in the actual forums here
https://api.quackduck.xyz/u/chrome_2018-09-17_19-45-45.png

it would be nice

**Comment by kanalumaddela** [comment]
their avatars are linked so it shud be an easy fix

**Comment by Marcuzz** [comment]
Done in next deployment
