### ISSUE TITLE
redirects 404 from /scripts/view/ID/whatever to /scripts/view/ID/

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#300]
Old V2 links were like : https://www.gmodstore.com/scripts/view/4858/ghomes-all-in-one-property-solution-buy-rent-from-npc-or-from-3d2d-panel

so just redirects 404 from /scripts/view/ID/whatever to /scripts/view/ID/ to fix all old links

**Comment by Marcuzz** [comment]
Fixed in next deployment
