### ISSUE TITLE
Job Progress minor issue

### ISSUE THREAD

**Issue by CraigHulme** [gmodstore/gmodstore-issues#301]
here 
https://api.quackduck.xyz/u/chrome_2018-09-17_19-38-04.png

I haven't applied to that job, yet the bar indicates I have. Maybe make the bar not visible until you apply and then show it at 1/4?

**Comment by ExtReMLapin** [comment]
rename your issue to be more descriptive

**Comment by CraigHulme** [comment]
it's understandable...?

**Comment by ExtReMLapin** [comment]
![](https://i.imgur.com/sV8J92D.png)

**Comment by Marcuzz** [comment]
Fixed in next deployment
