### ISSUE TITLE
Cannot check on Job Dashboard/Edit

### ISSUE THREAD

**Issue by FermentJoy** [gmodstore/gmodstore-issues#303]
Basically, when I tried to check on Job Dashboard this weird thing came up for Refund and I hit deny. Ever since then I try to check Job Dash board and I get this error https://gyazo.com/a8c8b372c7c02d8b0409a1607e8b2d7e

Same error appears when I hit edit.  I tried to see if I can change the refund option through settings but I could not find it. I also sent an email yesterday to Support and never got a response.

**Comment by Marcuzz** [comment]
Which job, and give us your link to your gmodstore profile please.

**Comment by FermentJoy** [comment]
https://www.gmodstore.com/users/76561198114135231


ANd the Job is basically all of them that I have posted.

**Comment by Marcuzz** [comment]
Fixed!

**Comment by FermentJoy** [comment]
Bless up thank you

**Comment by FermentJoy** [comment]
Yea the issue is back

**Comment by FermentJoy** [comment]
On this Job https://www.gmodstore.com/jobmarket/jobs/27808

**Comment by Marcuzz** [comment]
Can you try again?

**Comment by FermentJoy** [comment]
Works again. Thank you so much. Is their a reason why it broke again?

**Comment by Marcuzz** [comment]
Another developer changed something and forgot to take into account that Job Author's should always be able to see the dashboard.
