### ISSUE TITLE
403 on "purchased" (assigned) script

### ISSUE THREAD

**Issue by AnthonyFuller** [gmodstore/gmodstore-issues#305]
I have been assigned to Billy's no drm scripts.  For example, when I try to access the page for any of them I get a 403 error. But I can still download it through the my purchases page.
![image](https://user-images.githubusercontent.com/24512050/45646331-d977f180-baba-11e8-93c7-0c3b90bbc991.png)

-Anthony

SteamID64: 76561198215015615

**Comment by Marcuzz** [comment]
Fixed in next deployment
