### ISSUE TITLE
Pre-update applications set bid to budget

### ISSUE THREAD

**Issue by Greenhourglass** [gmodstore/gmodstore-issues#309]
I've noticed that when I view all the applications I've submitted before the update, all of them say the bid is what the job's budget was, even when I know I had bid something lower or higher. This is mainly only an issue because I can't find what price had been agreed upon on jobs that I have been doing since before the update.

**Comment by Marcuzz** [comment]
Yes. We screwed up when migrating all job applications and converting currency. I'm really sorry but we can't restore the old values anymore. You're gonna have to ask the other person what was agreed upon
