### ISSUE TITLE
Submitting a script sets the dollar amount as the cent amount.

### ISSUE THREAD

**Issue by Silhouhat** [gmodstore/gmodstore-issues#313]
Put in $4.99 as the price upon submitting a script at https://www.gmodstore.com/market/create
Once its page was created, the price displayed was $0.04

**Comment by Marcuzz** [comment]
Where does it show as $0.04, please give us a link

**Comment by Silhouhat** [comment]
It only happened when I submitted the script, I changed it right after noticing. This was the script: https://www.gmodstore.com/dashboard/addons/5755

**Comment by Marcuzz** [comment]
Okay, that's extremely weird. I will check it out later

**Comment by Marcuzz** [comment]
Fixed in next deployment
