### ISSUE TITLE
HUGE ISSUE MUST BE FIXED

### ISSUE THREAD

**Issue by xbread** [gmodstore/gmodstore-issues#316]
this new forum theme is fucking garbage. i'd recommend going back to the old one. also why would you release something to the main branch website if half the things are broken 🤔

**Comment by Thepenguin9** [comment]
Non-issue, spam

**Comment by DrPepperG** [comment]
Why would you spam the issues section with this

**Comment by Threebow** [comment]
They've been beta testing the site for months, you obviously can't find all the bugs with such a big recode if you don't let a bunch of people use it.

**Comment by ExtReMLapin** [comment]
retard

**Comment by Marcuzz** [comment]
This is some of the dumbest shit I've seen

**Comment by xbread** [comment]
mad
