### ISSUE TITLE
Script usage license not found

### ISSUE THREAD

**Issue by Threebow** [gmodstore/gmodstore-issues#319]
![](http://www.threebow.com/i/0901b1e8011a.png)

Observed here: https://www.gmodstore.com/market/view/5154/license

**Comment by ExtReMLapin** [comment]
https://www.gmodstore.com/market/view/4858/license same here it's in the .zip tho

**Comment by ExtReMLapin** [comment]
imo it should be high priority because of legal stuff

**Comment by Marcuzz** [comment]
I already fixed it but the fucking download server won't update

**Comment by Marcuzz** [comment]
It works, but only when signed in (quite obvious as it needs your steam64 id. will just have to deny access to the page when not logged in)
