### ISSUE TITLE
Mark all read 419 error

### ISSUE THREAD

**Issue by SrUnknown** [gmodstore/gmodstore-issues#320]
When you press "Mark all as read" it redirect you to 419 error website and it doesn't change the status of the notifications.

**Comment by ExtReMLapin** [comment]
no issue on my side give us your STEAMID64

**Comment by SrUnknown** [comment]
> no issue on my side give us your STEAMID64

76561198804494488
Here there's a video of it:
https://images.gscriptz.com/vid-0882-18-0918

**Comment by SrUnknown** [comment]
Seems to be fixed now, yesterday was redirecting to a 419 page.
### Yesterday video: https://images.gscriptz.com/vid-0882-18-0918

**Comment by ExtReMLapin** [comment]
I'm having this error right now
