### ISSUE TITLE
Migration didn't "export" the refunded scripts (refund button still here)

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#322]
https://www.gmodstore.com/users/76561198103106152/purchases?page=2
https://www.gmodstore.com/dashboard/addons/4858/purchases?page=6

![](https://i.imgur.com/TmbatyJ.png)
![](https://i.imgur.com/3gQAj3w.png)

I refunded the guy in V2 but the refund button is still here

![](https://i.imgur.com/1OLjLFK.png)

**Comment by Marcuzz** [comment]
Don't worry, it exported them. Fixed in next deployment
