### ISSUE TITLE
chrome Translation problems.

### ISSUE THREAD

**Issue by KiritoLifeF** [gmodstore/gmodstore-issues#323]
As I said.

Users of chrome browsers from different countries. After Google automatic translation, web sites will become blank.

![image](https://user-images.githubusercontent.com/26441281/45681322-cbd07380-bb6f-11e8-8787-015289d5d956.png)

**Comment by ExtReMLapin** [comment]
seems like a feature to me, i don't want to deal with people who can't speak english

**Comment by Marcuzz** [comment]
This is because of Vue, I don't actually think we can fix this so I've moved it to "Not sure how to fix"
