### ISSUE TITLE
Issue with a script 

### ISSUE THREAD

**Issue by Mbljbt1** [gmodstore/gmodstore-issues#324]
Some reason I'm banned from a script I bought it's called billy whitelist system.

**Comment by Marcuzz** [comment]
Contact the author of this addon instead.

**Comment by WilliamVenner** [comment]
![image](https://user-images.githubusercontent.com/14863743/45682977-fbfd1f80-bb39-11e8-85c8-36ae8cd0505d.png)

**Comment by Mbljbt1** [comment]
Carnt he's banned me

**Comment by Mbljbt1** [comment]
And blocked me

**Comment by WilliamVenner** [comment]
Hello, "can't" is not spelt with an "r" and I have not blocked anyone. Thank you!
