### ISSUE TITLE
Applicant cannot mark that I payed the job (After files are uploaded and price is negotiated)

### ISSUE THREAD

**Issue by UltraTechX** [gmodstore/gmodstore-issues#325]
Now that my jobs are finished, we went through the process of them uploading the files and such, but now it seems that they cannot mark that I paid them and still see "upload files" while I see a "pay" button

[Custom Intercom Model](https://www.gmodstore.com/jobmarket/jobs/27746):

What Old Bill Sees:
https://i.imgur.com/YbnDqJS.png

What I see:
https://imgur.com/a/KX5LDPH

----------------------------------------------------------------------------------------------------------------

[Map Optimization](https://www.gmodstore.com/jobmarket/jobs/27736):

What Taz Sees:
https://imgur.com/a/Iagg3Gn

What I see:
https://imgur.com/a/YhnzVSp

----------------------------------------------------------------------------------------------------------------

If this could be fixed that would be much appreciated, as I can't receive the files if they are unable to mark that I paid.

Many Thanks,
 - Ultra (Fat Gay)

**Comment by UltraTechX** [comment]
Also just as a FYI these people have already been paid in full, but assuming the issue is about them marking that I paid you should be able to assume that.

**Comment by Marcuzz** [comment]
Can you have Taz check within the upload files area for a "Ultra has paid me" button?

**Comment by UltraTechX** [comment]
> Can you have Taz check within the upload files area for a "Ultra has paid me" button?

Taz doesn't seem to be online right now, so I asked Old Bill to do it. He says the button its still the same and nothing changed when you click it.

**Comment by Marcuzz** [comment]
Is there absolutely nothing else in the upload files area? That's where the "has paid me" button should be. Ask him to take a screenshot please

**Comment by UltraTechX** [comment]
> Is there absolutely nothing else in the upload files area? That's where the "has paid me" button should be. Ask him to take a screenshot please

Here is a video Old Bill sent me, i could not view it from the website he gave me so i just uploaded it onto YouTube. https://youtu.be/LYKsQGUW2oo

**Comment by Marcuzz** [comment]
Alright. Give me a while to import a database backup where this scenario occurs so I can debug it :)

**Comment by UltraTechX** [comment]
It worked! He said he was able to mark that I paid, and I am now able to "download files", and when I click that I am able to download the Zip. Only problem now is we cant seem to find where to give each other rep, no options around the job page, applicant page, or our own profile's rep pages.

**Comment by Marcuzz** [comment]
Oh right. User reviews are not done yet. Had to put them on hold to fix other bugs in the meanwhile. You'll be able to do this at a later point
