### ISSUE TITLE
Links of the requirements text aren't clickable

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#326]
When you put the requirements of your script, if you want to put a link (to a Workshop content addon by example), the link isn't clickable which makes it less visible and then nobody of our buyers will see this when downloading the script.

![screenshot_20180918-140333_chrome](https://user-images.githubusercontent.com/42046569/45686805-679cb800-bb4d-11e8-8804-bf3f265eaa66.jpg)

Thanks.

**Comment by ExtReMLapin** [comment]
do some research before opening issues


#203

**Comment by DiablosCorp** [comment]
Closing.
