### ISSUE TITLE
Allowed to see each others ban history?

### ISSUE THREAD

**Issue by CyanRawr** [gmodstore/gmodstore-issues#328]
Are you supposed to be able to people ban history?
you can see them by just typing out the link manually 
https://www.gmodstore.com/users/xxxxxxxxxxxxxxxxxxxx/bans

**Comment by ExtReMLapin** [comment]
delet dis

**Comment by CyanRawr** [comment]
whats wrong with reporting this issue?

**Comment by ExtReMLapin** [comment]
well i want to use it

**Comment by Marcuzz** [comment]
Fixed in next deployment
