### ISSUE TITLE
Tickets show nothing

### ISSUE THREAD

**Issue by DrPepperG** [gmodstore/gmodstore-issues#330]
The past 2 tickets I have gotten have had -1 replies and nothing in it. It might also be creating 2 of the same thing with the title on one and the text on another. The second part might just be a coincidence idk.

![](https://i.ambigboy.xyz/zf96M.png)
![](https://i.ambigboy.xyz/T603C.png)

The last one has a response so that is why it is at 0
![](https://i.ambigboy.xyz/b9034.png)

Tried to create a ticket on title store and it gave me a 500 error, I even had my self removed from the team and tried it and it did the same thing
![](https://i.ambigboy.xyz/I81cW.png)
After a while it created it and no text was in it
![](https://i.ambigboy.xyz/n93eT.png)

**Comment by kanalumaddela** [comment]
@J0sh0nat0r 
`e0814f63a7d24e478ba403a509e5056d`

**Comment by Marcuzz** [comment]
Can you please report the issue when the 500 pops up on your screen and give us the Event ID? The event ID @kanalumaddela gave and the one in the picture are both invalid

**Comment by kanalumaddela** [comment]
@Marcuzz @J0sh0nat0r had deleted the log and mentioned something about something being owned by root. After that everything was fine. Dunno if anyone else is getting the issue after the time I commented, but it works atm.

**Comment by Marcuzz** [comment]
Okay. I will close this for now. reopen if it reocurrs.
