### ISSUE TITLE
You're making too many requests too quickly!

### ISSUE THREAD

**Issue by Crap-Head** [gmodstore/gmodstore-issues#333]
![image](https://user-images.githubusercontent.com/4314483/45711188-098dc600-bb89-11e8-9191-0785c1abbb0c.png)

I get this kinda of "error" message when I open around 5 tickets in different tabs, then reply to it and close it rather quickly after each other.

**Comment by Marcuzz** [comment]
Okay. I've upped the limit to two POST requests every 3 seconds from 1 every 3 in the next deployment
