### ISSUE TITLE
Bug with the ban centre for moderators

### ISSUE THREAD

**Issue by Crap-Head** [gmodstore/gmodstore-issues#334]
I am getting a "500 Internal Server Error" when trying to unban users.

Another thing which is really weird, is that when going through Moderation -> Ban -> Cancel it takes you to the actual bans page of the user (for example https://www.gmodstore.com/users/76561198095075535/bans when clicking "Cancel" on his guys "Ban" page. 

I'll walk you through it better if you need

**Comment by Crap-Head** [comment]
![image](https://user-images.githubusercontent.com/4314483/45712670-3348ec00-bb8d-11e8-9ff2-9b0300ac2c52.png)

It's actually all the 3 buttons on the right that gives the 500 error.

**Comment by Marcuzz** [comment]
I fixed the other issues in next deployment but I'm not sure what cancel button you mean?

**Comment by Crap-Head** [comment]
This is the first thing that shows up when you do "Moderation -> Ban" and then when you press Cancel it will show their list of bans. The order just seems strange?

**Comment by Marcuzz** [comment]
Where do you think it's logical for it to go?

**Comment by Crap-Head** [comment]
If you could change it so you go through Moderation  -> Ban and it displays the users bans (example this url https://www.gmodstore.com/users/76561198095075535/bans) - on this page it would have the "Create a ban" button and it would show. Once banned, return to the ban "history" url.

**Comment by Marcuzz** [comment]
I just realized you're confused because you can't see the "bans" tab which goes to the ban list and I'm confused because I can't see the Moderation -> ban button which goes to a page to ban the user. What the fuck

**Comment by Marcuzz** [comment]
Fixed in next deployment
