### ISSUE TITLE
last downloaded is shown as never all the time

### ISSUE THREAD

**Issue by kanalumaddela** [gmodstore/gmodstore-issues#335]
candyapple said he's already downloaded my shit and I know he did cause he shows in my webhook db

![](https://i.mdd.la/chrome_2018-09-18_16-08-39.png)

**Comment by ExtReMLapin** [comment]
can confirm

**Comment by Marcuzz** [comment]
Fixed in next deployment (user has to download again, a log was never inserted)

**Comment by ExtReMLapin** [comment]
maybe no one is downloading ur scripts kanal

**Comment by Marcuzz** [comment]
actually fixed in next deployment (for new downloads)
