### ISSUE TITLE
No notification when someone opens a PayPal dispute

### ISSUE THREAD

**Issue by Crap-Head** [gmodstore/gmodstore-issues#336]
Title says it all - someone opened an "unauthorized transaction" dispute on my script, and I received no notifications at all.

It's not possible for me to link the dispute to gmodstore without this, but here is his email though suzuku295@gmail.com

Everything is checked in the notification settings.

**Comment by kanalumaddela** [comment]
freemmaann has gotten a notification here (look at edit history): https://github.com/gmodstore/gmodstore-issues/issues/329

could it be the type of dispute or was this a chargeback instead?

**Comment by DrPepperG** [comment]
> 
> 
> freemmaann has gotten a notification here (look at edit history): #329
> 
> could it be the type of dispute or was this a chargeback instead?

He got it when the guy didn't even pay for it.

**Comment by Crap-Head** [comment]
That is indeed weird, but I am sure it is not a chargeback. Here is a screenshot of it, so devs can see exactly what it's about:
![image](https://user-images.githubusercontent.com/4314483/45718929-0dc4de00-bb9f-11e8-9b72-e99850b54f57.png)

I am also really confused why it is in his currency?

**Comment by handsomematt** [comment]
@Crap-Head did the dispute ever come through?

**Comment by Marcuzz** [comment]
Is the last one a `payment reversal` ?

**Comment by ExtReMLapin** [comment]
both of them were "payment reversal"

**Comment by Marcuzz** [comment]
That was fixed earlier today, right after this guy made his payment reversals. Closing
