### ISSUE TITLE
Can't Download Script

### ISSUE THREAD

**Issue by thovanic** [gmodstore/gmodstore-issues#338]
I bought the Script called UWeed and when I press the download button i get this error

Fatal error: Allowed memory size of 209715200 bytes exhausted (tried to allocate 192512 bytes) in /var/www/html/app/Download/AddonArchive.php on line 84

Fatal error: Allowed memory size of 209715200 bytes exhausted (tried to allocate 131072 bytes) in /var/www/html/vendor/sentry/sentry/lib/Raven/Client.php on line 1010

**Comment by kanalumaddela** [comment]
cause the addon is too big due to the filesize of the addons, matt is working on it
