### ISSUE TITLE
You can mark your uploaded script ticket as solved and curator can't do anything

### ISSUE THREAD

**Issue by Threebow** [gmodstore/gmodstore-issues#339]
![](http://www.threebow.com/i/192240b59168.png)

**Comment by Threebow** [comment]
Also blurry avatar for the locked notification

**Comment by kanalumaddela** [comment]
not blurry avatar, it just uses the icon size version from steam

**Comment by WilliamVenner** [comment]
yeah but it's blurry!

**Comment by Marcuzz** [comment]
You can no longer lock your own submission threads from the next deployment. But I don't get what you mean that the moderator can't do anything? I'm completely able to unlock the thread?
