### ISSUE TITLE
500 Internal Server Error: Reporting User Page

### ISSUE THREAD

**Issue by MrCraigTunstall** [gmodstore/gmodstore-issues#343]
500 Internal Server Error is given on the following link when you click on the "forums" hyperlink from within the page.
![d5f0d52accea9b923b1909863728d2df](https://user-images.githubusercontent.com/11096308/45755040-2cfe5280-bc15-11e8-952c-0b9439a43597.png)

https://www.gmodstore.com/help/reporting/reporting-users

**Comment by Marcuzz** [comment]
duplicate of #281
