### ISSUE TITLE
Grammar: This site not associated with Valve Corp.

### ISSUE THREAD

**Issue by Nyaaaa** [gmodstore/gmodstore-issues#360]
This site not associated with Valve Corp.

Should be 

This site is not associated with Valve Corp.

**Comment by Marcuzz** [comment]
Where does it even say this?

**Comment by Nyaaaa** [comment]
Before you login to the website!

**Comment by kanalumaddela** [comment]
that's steam own login button, complain to them

**Comment by Marcuzz** [comment]
That's Valve's own button. We can't edit that.

**Comment by Nyaaaa** [comment]
>           that's steam own login button, complain to them



>           That's Valve's own button. We can't edit that.

>           that's steam own login button, complain to them

Actually no it is not because I looked it's the websites logo, I did my research tyvm!

**Comment by Marcuzz** [comment]
Mate, it's literally right here: https://steamcommunity.com/dev

**Comment by Nyaaaa** [comment]
>Mate, it's literally right here: https://steamcommunity.com/dev 

Yeah nvm got confused!

**Comment by Doc1337** [comment]
tragedy

**Comment by Nyaaaa** [comment]
>Mate, it's literally right here: https://steamcommunity.com/dev

Complained to Valve thanks!
