### ISSUE TITLE
Review's pagination does not have any limit

### ISSUE THREAD

**Issue by Gabyfle** [gmodstore/gmodstore-issues#362]
Pagination in script reviews **has no limits**. This is a very *secondary bug*, but it is good to report it (I hope it hasn't already been reported, I haven't found anything similar)

![paginationbug](https://user-images.githubusercontent.com/18049206/45834960-f4d83c00-bd08-11e8-8470-fb7be6607632.png)

**Comment by kanalumaddela** [comment]
can confirm, you can go past the # of pages and even go into the negatives

**Comment by J0sh0nat0r** [comment]
Seems to be fixed.

**Comment by kanalumaddela** [comment]
Nah,  just checked

Going into the negatives leaves it at the 1st page, but going to a page number greater than what is there is blank
