### ISSUE TITLE
Copy and paste a name

### ISSUE THREAD

**Issue by Nyaaaa** [gmodstore/gmodstore-issues#363]
When you copy and paste a name on the discussion under a job a big line appears along side the name and not underneath the name + you can't reply to peoples post, You need a reply button but you have to copy and paste their name to reply!
Example underneath:
MysticSeagull _____________

**Comment by kanalumaddela** [comment]
where are you copying the name from, 99% sure it's cause it's copying the formatting on wherever that name is being copied from, it's hard to tell by the way you're describing it

**Comment by Nyaaaa** [comment]
I was copying it from a job discussion!

**Comment by kanalumaddela** [comment]
Highlight the name and clear the formatting using the button on the text editor
![](https://i.mdd.la/chrome_2018-09-20_15-58-46.png)

@Marcuzz maybe have the editor strip all formatting that doesn't exist in the toolbar?

**Comment by Nyaaaa** [comment]
Well I'd rather copy the name like in other forums and it removing the formatting automatically, I could just remove it manually but that gets a bit annoying sometimes!

**Comment by kanalumaddela** [comment]
i literally fucking said that underneath the picture

**Comment by Nyaaaa** [comment]
>i literally fucking said that underneath the picture

Okay, It leaves a big space after the name now, the long underline is gone.

**Comment by kanalumaddela** [comment]
> Okay, It leaves a big space after the name now, the long underline is gone.

no shit, now you're just being retarded, it removes the *formatting*, not the characters. there's this thing called a "backspace"

**Comment by Nyaaaa** [comment]
>no shit, now you're just being retarded, it removes the formatting, not the characters. there's this thing called a "backspace"
I'm not being retarded it's an issue that needs to be fixed it doesn't happen on other forums.

**Comment by J0sh0nat0r** [comment]
You're copying a link into the textbox, so it will be formatted as such
