### ISSUE TITLE
Error Script Edition in User

### ISSUE THREAD

**Issue by Offshorp** [gmodstore/gmodstore-issues#364]
Hello,

When I want to edit my script, I'm on a page with this:

**403 No Permission
You're not allowed to do that...

Click here to go back. Or click here to return to the index page.

Issue Tracker support@gmodstore.com @gmodstore
Terms of Service Privacy Policy**

I know, it's a little bug but his not good for users who want to be a content creator on GmodStore.

- Offshorp

**Comment by J0sh0nat0r** [comment]
Should be fixed.
