### ISSUE TITLE
Can't search via peoples name!

### ISSUE THREAD

**Issue by Nyaaaa** [gmodstore/gmodstore-issues#366]
Can't search via peoples name!

I would really love this feature so I could look to see what people have been creating, Instead of going on their profile and looking, Or having the trouble of finding that person in google or gmodstore looking in the marketplace and looking via that way, I also think the search should be able to search peoples profiles!

**Comment by kanalumaddela** [comment]
https://www.gmodstore.com/users/browse ????

**Comment by ExtReMLapin** [comment]
![](https://sweetmarzipan.files.wordpress.com/2008/08/ralph-eating-paste.gif)

**Comment by Nyaaaa** [comment]
https://www.gmodstore.com/users/browse 

403 No Permission 
You're not allowed to do that...
Click here to go back. Or click here to return to the index page.

Seems like most things are for the mods and owners only but yet we can still see some of the links!

**Comment by ExtReMLapin** [comment]
lol wtf

**Comment by kanalumaddela** [comment]
what's your gms profile

**Comment by Nyaaaa** [comment]
https://www.gmodstore.com/users/76561197972075795

**Comment by Marcuzz** [comment]
This is intentional though @kanalumaddela
