### ISSUE TITLE
Refunds logs duplicated...

### ISSUE THREAD

**Issue by Yepco71** [gmodstore/gmodstore-issues#371]
Hello,

I have found a little graphic problem on the event log.

The refunds logs are duplicated...

Screen : 
![image](https://user-images.githubusercontent.com/17533693/45852970-135b2900-bd43-11e8-8bd7-4dbba3c98f79.png)

Sincerely.
Yepco.

**Comment by ExtReMLapin** [comment]
Yer late buddy

🍔

**Comment by Marcuzz** [comment]
These are very very old, not related to v3
