### ISSUE TITLE
Events Log spam 

### ISSUE THREAD

**Issue by SrUnknown** [gmodstore/gmodstore-issues#373]
Ok i figured it out how to re-create this issue, you just go to Purchases and revoke someones permission to the addon, it will stuck at "loading" some request or something but at events logs it will be registering [spamming] it. i didn't know about this until i checked that i have 18k logs.

Here's a video:
https://i.iamschiaffino.com/vid-3076-21-0918

As you can see the purchases website is "loading" and the events log website is filled with 293432948392 logs.

#RemoveSpammedLogsPlsTy.

**Comment by Marcuzz** [comment]
This has been fixed
