### ISSUE TITLE
[Mobile Only] Second nav bar on products

### ISSUE THREAD

**Issue by Doc1337** [gmodstore/gmodstore-issues#374]
Whenever you go to a product (on mobile) there is a second nav bar right under the main one. I found that very confusing when for example looking for discussions. I would suggest that you remove the mobile button (that's used to show/hide) or use another bootstrap element that was made for this - navbar tabs

https://getbootstrap.com/docs/4.0/components/navs/#tabs

**Comment by Doc1337** [comment]
https://imgur.com/a/vftw41u

**Comment by Doc1337** [comment]
Mainly a visual change since there are not a lot of tabs that it would need mobile button

**Comment by ExtReMLapin** [comment]
pretty sure it's to save space

**Comment by Doc1337** [comment]
Yes but there is enough space for the whole navbar without the button

**Comment by Gabyfle** [comment]
I don't know what is planned to be mobile-friendly, but I think a submenu like in Github would be perfect :
![screenshot_20180921-194839](https://user-images.githubusercontent.com/18049206/45897516-9fb72b80-bdd7-11e8-8c5b-e4f6252d52f1.jpg)

**Comment by Doc1337** [comment]
> I don't know what is planned to be mobile-friendly, but I think a submenu like in Github would be perfect :
> https://user-images.githubusercontent.com/18049206/45897516-9fb72b80-bdd7-11e8-8c5b-e4f6252d52f1.jpg

Yes exactly! That is what I am looking forward to.

**Comment by Marcuzz** [comment]
Fixed in 3.0.93
