### ISSUE TITLE
Gift a addon

### ISSUE THREAD

**Issue by PwnedCax** [gmodstore/gmodstore-issues#375]
Hello , I would like to point out that for example if I have purchased an addon that is currently disabled, I can gift it to someone else 

I point this out to you because an idiot wants a gift in exchange for reporting the bug ( cc Yepco) 

Thank's

**Comment by ExtReMLapin** [comment]
> ( cc Yepco)

LE MANGEUR MASQUÉ

![](https://i.imgur.com/lHDJ9D4.png)

![](https://i.imgur.com/921Y04r.png)

**Comment by Marcuzz** [comment]
This is fixed
