### ISSUE TITLE
Suggestion: Events log - Discussion

### ISSUE THREAD

**Issue by Nyaaaa** [gmodstore/gmodstore-issues#376]
Suggestion: Events log - Add the current discussion you're discussing in addons, But only the addon name - with discussion next to it so we can see if their is any new post on the current addon we posted for as I receive no new notifications for the discussion for new post!

**Comment by kanalumaddela** [comment]
unnecessary

**Comment by Nyaaaa** [comment]
Why is it unnecessary I'd like to know who's addon I've posted on instead of searching it, Because I can't remember!

**Comment by Marcuzz** [comment]
This probably won't happen
