### ISSUE TITLE
Add a "knowledge base" tab near the discussion tab

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#377]
Add a "knowledge base" tab near the discussion tab so people can easily access it

**Comment by kanalumaddela** [comment]
I say it should be on the right side are next to the support button. Dunno if it should show no matter whether a user owns it or not.

**Comment by ExtReMLapin** [comment]
this idea is just to make it more visible

**Comment by kanalumaddela** [comment]
The sidebar is definitely more noticeable than the new sub nav to users

**Comment by Marcuzz** [comment]
Duplicate of your own issue, #282
