### ISSUE TITLE
In the "help" section, searching for stuff also returns addons "knowledge base" articles

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#378]
https://www.gmodstore.com/help
Simple example : 

![](https://i.imgur.com/7Lp6P8U.png)

Link is : 

gmodstore.com/help/how-to-correctly-add-houses-apartments/how-to-deal-with-no-room-to-place-the-front-door-panel

It returns 404 because the real link is : 

gmodstore.com/help/**addon/4858**/how-to-correctly-add-houses-apartments/how-to-deal-with-no-room-to-place-the-front-door-panel

**Comment by kanalumaddela** [comment]
This was probably cause when the knowledgebase was broken to where you can have global urls instead of addon specific.

**Comment by Marcuzz** [comment]
Fixes in next deployment
