### ISSUE TITLE
Timed out when trying to unrevoke + 500 when trying to revoke + wierd revoked addon with no trace in logs

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#384]
Whole story here  

A guy got ezjobs revoked

I do not remember revoking the license

can't find shit about his revoked license in the logs (in my own logs at least)

When trying to unrevoke it, it just loads and after a minute gives me a 524 error

https://www.gmodstore.com/dashboard/addons/3071/purchases?page=89

I'm trying to unrevoke enzio's license

![](https://i.imgur.com/sjjqmUk.png)

**Comment by ExtReMLapin** [comment]
Also, error 500 when trying to revoke

**Comment by Marcuzz** [comment]
This should work now?

**Comment by ExtReMLapin** [comment]
Yes both fixed !
