### ISSUE TITLE
Team Reputation Issue

### ISSUE THREAD

**Issue by Zephruz** [gmodstore/gmodstore-issues#391]
I'm not sure if this applies elsewhere among the site and not just team reputation, but I noticed this on one of my teams.
Our team has a 5.00 average on **35 reviews**, which would logically mean that a majority - if not all - reviews are positive. However, under the reputation card it says that there's only 15 reputation, which should be 30+.

![image](https://user-images.githubusercontent.com/16161622/45923058-0a806980-bea1-11e8-84e6-9bb2fd2b2607.png)

**Comment by HuntingVillager** [comment]
This is probably fixed. If it's not feel free to ping me.
