### ISSUE TITLE
[SITE TICKET] Zip file must be a Zip File.

### ISSUE THREAD

**Issue by robertdrakedennis** [gmodstore/gmodstore-issues#403]
[https://www.gmodstore.com/moderator/tickets/107022](https://www.gmodstore.com/moderator/tickets/107022)

> I'm trying to upload a addon in a file called 'PolarX.zip'. File extensions are shown, when completing the form it provides a error saying "Zip file must be a Zip File."

**Comment by Doc1337** [comment]
~~Upload it to mediafire~~

As someone who is atlas i would expect you to make over-engineered solution like buying a gmodsto.re domain and using it as filehosting service.

**Comment by HuntingVillager** [comment]
Fixed
