### ISSUE TITLE
ticket notifications links

### ISSUE THREAD

**Issue by kanalumaddela** [gmodstore/gmodstore-issues#404]
when getting notifications for tickets from customers, they link to the site ticket area instead of the dashboard area
https://www.gmodstore.com/notifications/637edf17-e20e-4a30-b7bf-a969676bfe85

redirects to https://www.gmodstore.com/help/tickets/view/107036 instead of 
https://www.gmodstore.com/dashboard/tickets/107036

this can get confusing cause then when you *think* you're going to see your customer tickets, you end up opening the site tickets which in most cases will show none
![](https://i.mdd.la/chrome_2018-09-23_22-39-27.png)

customer tickets should only link and be accessible from the dashboard route

**edit**
i see now that customers use the /help/ route while creators use the /dashboard/ route, but it's still confusing for creators to find their tickets

**Comment by Marcuzz** [comment]
Fixed
