### ISSUE TITLE
403 On viewing user list

### ISSUE THREAD

**Issue by Doc1337** [gmodstore/gmodstore-issues#406]
hey everyone doc again, well basically today I am lamenting about that 403 error that comes up for normal user, if you click that link in footer that says XX,XXX Members registered it gives 403 error, however in discord you can just do !gms to lookup users, and I remember that in V2 i was also looking up users so please fix

**Comment by Doc1337** [comment]
You must be a regular user, not a content creator.

https://www.gmodstore.com/users/browse

**Comment by Jpofin** [comment]
http://i.epvpimg.com/eyQGfab.png

However it does work for me, even as a regular user.

**Comment by Marcuzz** [comment]
@Jpofin you're probably a job author

Regular users are not allowed to browse users
