### ISSUE TITLE
Duplicate log

### ISSUE THREAD

**Issue by enzio53** [gmodstore/gmodstore-issues#408]
![telechargement 3](https://user-images.githubusercontent.com/10324803/45966767-59a6d580-c02c-11e8-8f81-dd6e9a610f49.png)

> :user0.name unrevoked :user1.name's access to addon: ez Job Creator - In-game job generator/creator

the same log on 506 page

**Comment by Marcuzz** [comment]
Give me a direct link to that page please.

**Comment by enzio53** [comment]
https://www.gmodstore.com/users/76561198144440215/events

**Comment by ExtReMLapin** [comment]
NOT ME AT ALL

**Comment by ExtReMLapin** [comment]
also @enzio53 i couldn't find in my logs when ezjobs was revoked so I doubt it was me, if you can find it, it would be cool 👍

**Comment by Marcuzz** [comment]
Fixed
