### ISSUE TITLE
Ticket "open / solved / all" filter is wrong when you are on the page initially

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#410]
So when you go in your tickets, you see all the tickets which are currently opened, while the filter is saying that it's filtered by "All tickets".
![xap9](https://user-images.githubusercontent.com/42046569/45969564-5b749700-c034-11e8-963b-aea56bd3dede.png)

If it was only this I would not have created a issue report (even if the filter is wrong), but basically if you want to see all tickets you are forced to select the "Open" or "Solved" tickets and then select for real the "All tickets" box and HERE it will show you all the tickets. Basically the ticket filter is a bit broken, or at least it should be by default at "Open tickets" to fix everything.

**Comment by Marcuzz** [comment]
Fixed
