### ISSUE TITLE
Phone layout broken when I click on my logo in the topnavbar

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#412]
When you're on the gmodstore homepage, everything looks good
![screenshot_20180925-101930_chrome](https://user-images.githubusercontent.com/42046569/46001858-b9dd5c00-c0ac-11e8-9e63-b559f8c8fabf.jpg)
However, when I click on my logo, the "Diablos's box"  makes it looks ugly with a blank space at the right.
![screenshot_20180925-101940_chrome](https://user-images.githubusercontent.com/42046569/46001949-f01adb80-c0ac-11e8-8040-9decf0922ae8.jpg)

**Comment by Marcuzz** [comment]
Fixed
