### ISSUE TITLE
Terms of Service and Privacy Policy

### ISSUE THREAD

**Issue by Mitch123413** [gmodstore/gmodstore-issues#413]
Hay. I couldn't find anything about this. So hopefully this is new.

When i click Privacy Police and Terms of conditions on the footer it brings me to a blue 500 Error Page. 
[Image](https://cdn.discordapp.com/attachments/466682229465284629/494165309435936809/unknown.png)

Thanks for you help! The website looks great.

If the link didn't work. try https://cdn.discordapp.com/attachments/466682229465284629/494165309435936809/unknown.png

**Comment by Mitch123413** [comment]
It changes each time but here.
9da8d099449446a2b3fd2221346bb2f2 -- event id 1 for terms of service

 2d953bc052b3421db7686e6810e2dfaa -- event id 2 for privacy policy

**Comment by J0sh0nat0r** [comment]
Fixed in the upcoming release (3.0.48)
