### ISSUE TITLE
Navbar Feedback for User Experience Improvements

### ISSUE THREAD

**Issue by moatato** [gmodstore/gmodstore-issues#414]
Hey! Could you do something for the dropdown differences on the navbar please? Marketplace has a hover dropdown, but all the other navbar dropdowns require you to click. (leaving users to expect one or the other)

My initial experience for the new site was blemished when hovering over Community (and Profile) subsequent to hovering over Marketplace and being presented with a dropdown right away. My weird human brain ergo expected a dropdown to appear without clicking. Also, a cool ux improvement would be to add down arrows like the Community dropdown has, to the Marketplace dropdown and account picture dropdown. (and if u want to be even cooler, u could add icons and descriptions to the other dropdowns like the Marketplace one has, for super slick consistent boss navbar!!)

p.s. totally sorry if this sounds like really dumb and pompous, you guys did an awesome job on this new site and i really appreciate it a lot 🍓🌸

**Comment by Marcuzz** [comment]
Done in the next update
