### ISSUE TITLE
Uploading any images/header images wont work

### ISSUE THREAD

**Issue by FloopyDisk** [gmodstore/gmodstore-issues#415]
So I'm trying to create a new addon and when I upload my header, it still says choose a file. Before that it pops up with a resizer then when I click finish, it doesn't upload.
I can only upload my addons zip file. I cant publish my script without uploading a image

**Comment by ExtReMLapin** [comment]
record a video @MicahJinkerson

**Comment by MicahJinkerson** [comment]
> record a video @MicahJinkerson

https://youtu.be/MvNmyp26j04

**Comment by HuntingVillager** [comment]
Fixed
