### ISSUE TITLE
i have 434 pages of shit logs

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#418]
from https://www.gmodstore.com/users/Lapin/events?page=1

to 

https://www.gmodstore.com/users/Lapin/events?page=433

![](https://i.imgur.com/a9eWM8l.png)

**Comment by ExtReMLapin** [comment]
was caused by #384

**Comment by J0sh0nat0r** [comment]
Duplicate of #408
