### ISSUE TITLE
Displayed addon average rating is incorrect

### ISSUE THREAD

**Issue by WilliamVenner** [gmodstore/gmodstore-issues#420]
https://www.gmodstore.com/market/view/1599 - 4.93 star average, 4 stars displayed site-wide

https://www.gmodstore.com/market/view/2306 - 4.97 star average, 4 stars displayed site-wide

ffs!

**Comment by ExtReMLapin** [comment]
high priority

**Comment by Marcuzz** [comment]
Fixed in next deployment
