### ISSUE TITLE
Cant open creator dashboard

### ISSUE THREAD

**Issue by M1800** [gmodstore/gmodstore-issues#425]
When i press  the dashboard button this pops up, https://cyanic.eu/i/5RJ0Wk2P9.png (500 internal server error)
Worked like 2 days ago

**Comment by J0sh0nat0r** [comment]
Please send us an event ID

**Comment by M1800** [comment]
2aaa0eb768e6483ab41aad5dacbdcf91

**Comment by Marcuzz** [comment]
Try again now

**Comment by M1800** [comment]
Not working :/
8835d5e1eef54725bd915c3a3c30997f

**Comment by Marcuzz** [comment]
Try again now

**Comment by Marcuzz** [comment]
Nevermind. I broke it again

**Comment by Marcuzz** [comment]
Try again in about six minutes.

**Comment by M1800** [comment]
Working. Thanks :)
