### ISSUE TITLE
I should not be able to see the [i] transaction button if i'm not the seller

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#427]
https://www.gmodstore.com/users/76561198054989316/purchases

![](https://i.imgur.com/AntTZIZ.png)

**Comment by kanalumaddela** [comment]
To add onto this, I think that button should show when a user views the page themselves and link their transaction info because this tiny spot doesn't help them find it:

![](https://i.mdd.la/chrome_2018-09-29_14-34-20.png)

**Comment by Marcuzz** [comment]
The user can't use that button anyway. That's a seller transaction ID. I've already fixed the "I" showing for everyone.
