### ISSUE TITLE
Job Reputation is displayed incorrectly

### ISSUE THREAD

**Issue by dannyf127** [gmodstore/gmodstore-issues#435]
![image](https://user-images.githubusercontent.com/21001224/46344377-c7876a00-c5f5-11e8-9cff-9428c3bdad94.png)

![image](https://user-images.githubusercontent.com/21001224/46344373-c35b4c80-c5f5-11e8-969d-db12e690a988.png)

**Comment by Marcuzz** [comment]
I'm not sure what's wrong here, 70 + 27 = 97

User reputation is job reputation.

**Comment by dannyf127** [comment]
“Split across 6 addons and 12 jobs”

**Comment by Marcuzz** [comment]
Oh, it doesn't count applications I think, could that be the issue. i.e you have 12 jobs, but the remainder of the 27 are from applications?
