### ISSUE TITLE
Free advertising on purchase page

### ISSUE THREAD

**Issue by Threebow** [gmodstore/gmodstore-issues#436]
I can create a disabled addon and give it some banners and assign it to people and it will display the full banner on the top of their purchases page, effectively free advertising.

Script: https://www.gmodstore.com/market/view/5760

These are the three people who I've assigned it to (with permission):
https://www.gmodstore.com/users/devultj/purchases
https://www.gmodstore.com/users/kanalumaddela/purchases
https://www.gmodstore.com/users/atlas/purchases

**Comment by ExtReMLapin** [comment]
In other words, non-mod-validated addons should not be visible on "purchases" page

**Comment by kanalumaddela** [comment]
I mean ***denied*** addons don't show unless you're assigned the addon. I don't know if the same applies to newly submitted addons.

**Comment by Marcuzz** [comment]
So you want the addon to just not appear at all if it's denied? That's kind of weird too

**Comment by WilliamVenner** [comment]
this is why there are rules?

**Comment by Threebow** [comment]
> So you want the addon to just not appear at all if it's denied? That's kind of weird too

I think it would be fine if it showed disabled addons that were previously sold.

**Comment by HuntingVillager** [comment]
Fixed
