### ISSUE TITLE
Search results should have a better ordering

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#438]
Search results should have a better order

Best would be to rank it by popularity/sales

**Comment by handsomematt** [comment]
Best would be by relevance :)

**Comment by ExtReMLapin** [comment]
True, also it would be nice to have a v2-like reseach system added to the current-one, pressing enter would redirect to the result page showing the addons.

**Comment by ExtReMLapin** [comment]
![](https://i.imgur.com/2LnJm3r.png)

no good

**Comment by WilliamVenner** [comment]
Measurement of relevance in order of importance:

1. Wishlist
2. Popularity (sales, ratings)
3. When the script was last updated
4. Search text relevance to script title

**Comment by Threebow** [comment]
The "popularity" should be determined by addon views over how long the addon has been on the site for. Can also do the same for addon sale and review frequency

**Comment by J0sh0nat0r** [comment]
Fixed in upcoming release.
