### ISSUE TITLE
You should not be able to buy the DLC if you don't own the base addon

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#448]
You should not be able to buy the DLC if you don't own the base addon

**Comment by DiablosCorp** [comment]
Except if the DLC is paid to be gifted to someone who has the base addon

**Comment by Marcuzz** [comment]
This is intentional incase a server owner has a certain addon but a co-owner wants to buy the DLC but doesn't want to gift
