### ISSUE TITLE
Review notifications just go to the front page

### ISSUE THREAD

**Issue by Crap-Head** [gmodstore/gmodstore-issues#451]
If you click on a notification for a review, it will not take you to the actual script/review section. It will just redirect you to https://www.gmodstore.com/ instead

**Comment by Crap-Head** [comment]
Considering the script number is already in the notification "DrKleiner posted a review on #5537 Advanced Keys (Vehicle Alarm, Custom Models & More)" - this should be extremely simple to fix?

**Comment by Marcuzz** [comment]
Fixed in next release
