### ISSUE TITLE
Rep isn't correct 

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#453]
i should have 150 but it only shows 133

![](https://i.imgur.com/gND4XnJ.jpg)

Edit : okay even is the gHomes DLC owned by Meow and I isn't counted there is still a gap

**Comment by ExtReMLapin** [comment]
Or it is because of the manually assigned licenses ?

**Comment by ExtReMLapin** [comment]
NIGGA WHAT

i got a review and it went from 133 to 131

![](https://i.imgur.com/erifjpm.png)

**Comment by NeithCorp** [comment]
every new positive review that should give you +rep seems to do the opposite, it removes the rep from you. i wonder if 1 star reviews do the opposite as well lol

**Comment by Crap-Head** [comment]
@NeithCorp +1 rep gives -2 rep at the moment
