### ISSUE TITLE
/api/scripts/purchases/ should have country_code

### ISSUE THREAD

**Issue by WilliamVenner** [gmodstore/gmodstore-issues#47]
Adding the users' country codes in /api/scripts/purchases/ would be useful for statistics so I could find out what countries my customers are from.

This could be done by iterating through /api/scripts/purchases/ and using /api/users/search/steam64/ but that's A LOT of requests.

**Comment by HandsomeMatt** [comment]
Should this be the location at the time of purchase dependent on their geoip or whatever they choose for VAT?

**Comment by WilliamVenner** [comment]
GeoIP, just like how ScriptFodder does it on the user page now.
