### ISSUE TITLE
Content Creators should always be able to see a user's SteamID64 on their profile

### ISSUE THREAD

**Issue by WilliamVenner** [gmodstore/gmodstore-issues#471]
For example, with this user: https://www.gmodstore.com/users/Im-So-Dank

I needed this user's SteamID64 for some leaker drama bullshit, but I wasn't able to get it because he disabled his Steam Profile link and also set a URL slug. Therefore content creators+ should be able to see the profile's SteamID64 somewhere on the page.

edit: I have since realised that the steamid64 is actually in the page html, but still :D

**Comment by Marcuzz** [comment]
Added in next deployment
