### ISSUE TITLE
Content Creator whilst addon is pending

### ISSUE THREAD

**Issue by confuseth** [gmodstore/gmodstore-issues#475]
## Expected Behavior
Not being able to be put on Content Creator whilst my only addon is on pending
Not being able to view other peoples purchases

## Actual Behavior
Well, I was put to Content Creator on my profile, only the tag not the badge, when I submitted my addon,
I can also see other peoples purchases
Not sure if this is intended but I believe not

## Steps to Reproduce the Problem
As above

**Comment by HuntingVillager** [comment]
This is intended behavior.
