### ISSUE TITLE
Can't Pay Without Paypal

### ISSUE THREAD

**Issue by PutItOnTheList** [gmodstore/gmodstore-issues#478]
When i try to purchase something without logging into paypal it tells me to login?

**Comment by kanalumaddela** [comment]
So login

**Comment by HuntingVillager** [comment]
I'm unsure what the issue is? PayPal is the only payment method, however you can link credit cards to your PayPal to pay with a credit card. However you'll need a PayPal account.

**Comment by PutItOnTheList** [comment]
> So login
No? because it's not my credit card that im buying with?

**Comment by PutItOnTheList** [comment]
> I'm unsure what the issue is? PayPal is the only payment method, however you can link credit cards to your PayPal to pay with a credit card. However you'll need a PayPal account.

You can pay with debit card through paypal without logging in, it just isn't working, ive bought addons with this method many times before.

**Comment by HuntingVillager** [comment]
Could you please link the addon?

**Comment by kanalumaddela** [comment]
Also your gmodstore profile so we could see if there's an issue with your account itself*

**Comment by PutItOnTheList** [comment]
https://www.gmodstore.com/market/view/3845
https://www.gmodstore.com/users/76561198281008490

**Comment by PutItOnTheList** [comment]
![image](https://user-images.githubusercontent.com/45329873/49344300-180a5a80-f66d-11e8-822c-56c0dfc0dcfa.png)
Heres what i get to, then i hit that and it tells me to login
I have no clue what that 'OR' thing is

**Comment by HuntingVillager** [comment]
This seems to be a PayPal issue. You'll have to contact PayPal if you want this fixed, we can't do anything about this.
