### ISSUE TITLE
Link to team in license is broken (teams/view/ID) instead of  (team/ID) so make a redirection

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#484]
Title

https://www.gmodstore.com/market/view/4858/license/76561198146446970

Since it's already this way in a ton of licenses, a redirection would be nice

**Comment by ExtReMLapin** [comment]
WORK FASTER JOSH YOU LAZY ASS

**Comment by HuntingVillager** [comment]
Please be so kind to follow the given template next time :)

**Comment by ExtReMLapin** [comment]
fuuuckkk offfff

**Comment by HuntingVillager** [comment]
Fixed
