### ISSUE TITLE
Can not see reputation

### ISSUE THREAD

**Issue by XxLMM13xXgaming** [gmodstore/gmodstore-issues#53]
So basically i think this was because of my ban (shitstorm with alex) but i am not sure here is the ban

http://i.imgur.com/TrnGtzu.png (should have ended)

How i cant see the rep given..

http://i.imgur.com/fX9BioS.png

Note that i cant see this page on anyone...

**Comment by WilliamVenner** [comment]
scriptfodder bugs aren't going to carry into gmodstore

**Comment by XxLMM13xXgaming** [comment]
Did not know if this was already known

**Comment by ATomIK** [comment]
stop getting banned

**Comment by XxLMM13xXgaming** [comment]
The ban was from something very stupid
