### ISSUE TITLE
Unreadable links in jumbotron on main page

### ISSUE THREAD

**Issue by GGG-KILLER** [gmodstore/gmodstore-issues#57]
The links on the jumbotron in the home page (when not logged in, have not tested when logged in) cannot be read due to the text color (black text with very dark image part):
![image](https://cloud.githubusercontent.com/assets/5892127/23802787/21c88474-0593-11e7-97f1-c2592990fd98.png)

This happens from 683x319 to 1821x850. In 780x364 it is still readable but starts to blend with the background tree.

Measurements made with the following code:
```javascript
let winSize = document.createElement ( 'div' );
winSize.style.top = '0';
winSize.style.right = '0';
winSize.style.backgroundColor = 'rgba(255,255,255, 0.5)';
document.body.appendChild ( winSize );
setInterval ( ( ) => winSize.innerHTML = `${window.innerWidth}x${window.innerHeight}`, 200 );
```

**Comment by WilliamVenner** [comment]
it doesn't matter. this isn't going to be here when gmodstore is released.

**Comment by GGG-KILLER** [comment]
@WilliamVenner  It's still there though?

**Comment by WilliamVenner** [comment]
gmodstore has not been released........ ScriptFodder has simply been rebranded

please read ffs, there's literally a massive alert at the top of the page

https://www.gmodstore.com/community/threads/2643-scriptfodder-gmodstore-explained

**Comment by GGG-KILLER** [comment]
There's no banner showing up to me.
