### ISSUE TITLE
Random "USERNAME has just purchased MY_SCRIPT_NAME"-Messages

### ISSUE THREAD

**Issue by Wolfbyte-dev** [gmodstore/gmodstore-issues#58]
I get randomly "USERNAME has just purchased MY_SCRIPT_NAME"-messages (sometimes more than 1 from a person). But they already purchased my script before a few months/weeks...

**Comment by Wolfbyte-dev** [comment]
Is there any dev alive :/ ?

**Comment by Marcuzz** [comment]
This is something that is caused by PayPal and not us, of course we could add a check if the purchase has already gone through but it's such an ugly "fix" for something that really shouldn't be happening on PayPal's end.

**Comment by Wolfbyte-dev** [comment]
Yea that would be nice ;)

**Comment by bloodless2010** [comment]
Marcuzz, shouldn't the transaction ID be checked if it's already processed as a security feature? For example, if someone buys a script, somebody else could potentially use the same txn ID.. there is a flaw with the IPN clearly..

**Comment by Marcuzz** [comment]
I don't think you understand how the IPN works, there's a handshake that gets done when the IPN URL is reached. Our server sends the response back to PayPal to check if the signed key is valid. You can't just reuse a txn id like that.
