### ISSUE TITLE
Purchased Scripts not purchased?

### ISSUE THREAD

**Issue by Antipli** [gmodstore/gmodstore-issues#60]
so i bought multiple scripts like usual and waited couple of hours didnt show up so i could download then so i went to sleep and it still hasnt said i can download them or that i even purchased them.

here are the trans:

(Morpheus)
Receiver email: redacted
Amount: $6.00 USD
Transaction date: May 17, 2017
Status: Completed
Transaction ID: 4KF2049522545192E

(splitload)
Receiver email: redacted
Amount: $2.59 USD
Transaction date: May 17, 2017
Status: Completed
Transaction ID: 9Y964727S0714540V

(Civs)
Receiver email: redacted
Amount: $6.00 USD
Transaction date: May 17, 2017
Status: Completed
Transaction ID: 0EF50788DM930972E

(blasthud)
Receiver email: redacted
Amount: $3.00 USD
Transaction date: May 17, 2017
Status: Completed
Transaction ID: 11Y20918VT4138742

(ez jobs)
Receiver email: redacted
Amount: $5.70 USD
Transaction date: May 17, 2017
Status: Completed
Transaction ID: 6TJ81536W3752294V

**Comment by Marcuzz** [comment]
Hi. Have you not seen the giant red warning on top of the website?

https://www.gmodstore.com/community/threads/2946-notice-17-05-2017-purchase-delays

**Comment by Antipli** [comment]
nope!

**Comment by ExtReMLapin** [comment]
Hey can you delete this message, we're getting spammed because of you .

**Comment by Marcuzz** [comment]
I redacted all email addresses from the issue.
