### ISSUE TITLE
Sending forum replies seems to do nothing

### ISSUE THREAD

**Issue by TrixterTheTux** [gmodstore/gmodstore-issues#71]
Page doesn't refresh, reply doesn't get posted. Just gets stuck at this:
![owo](https://maho.is-a-good-waifu.com/ed895b.png)
(Seems to happen only on old threads unless this was just fixed?)

**Comment by Marcuzz** [comment]
can you link me to a thread where this happens?

**Comment by TrixterTheTux** [comment]
Can't reproduce anymore, I guess this was related to the fixes with permissions you did before? (Or it was just caching on laptop) If it happens again, I'll just reopen this.
