### ISSUE TITLE
Deleting a team redirects you to the same page creating a 404 error.

### ISSUE THREAD

**Issue by OwjoTheGreat** [gmodstore/gmodstore-issues#78]
After you delete a team, it redirects you to the same team page. Leaving you on a 404 error.

I guess it should redirect you to the general team page instead?

**Comment by OwjoTheGreat** [comment]
It seems that if the user responds, the notification goes away. But then if you reply, the notification comes back and won't leave again.

**Comment by J0sh0nat0r** [comment]
Thanks for the report! This bug has been fixed in the next release
