### ISSUE TITLE
Super long posts hang on posting

### ISSUE THREAD

**Issue by Threebow** [gmodstore/gmodstore-issues#86]
Button just goes light

![](http://www.threebow.com/i/9ef3cd219465.png)

**Comment by IamOmni** [comment]
A short post also gave me light button then a 403 page.

Afterwards logs me out.

**Comment by Marcuzz** [comment]
This is because you've reached the max limit of characters, hence the 403. Will display an error message soon so I'm leaving this issue open

**Comment by ExtReMLapin** [comment]
`VM267:1 POST https://beta.gmodstore.com/community/posts/41534 422 ()
(anonymous) @ VM267:1
(anonymous) @ app.js?id=be62b8fed3ae4954fef2:1
(anonymous) @ vendor.js?id=83d2b662603978fa3f1c:1
e.exports @ vendor.js?id=83d2b662603978fa3f1c:1
e.exports @ vendor.js?id=83d2b662603978fa3f1c:1
Promise.then (async)
XmWM.s.request @ vendor.js?id=83d2b662603978fa3f1c:1
s.(anonymous function) @ vendor.js?id=83d2b662603978fa3f1c:1
(anonymous) @ vendor.js?id=83d2b662603978fa3f1c:1
(anonymous) @ app.js?id=be62b8fed3ae4954fef2:1
I3G/.e.$emit @ vendor.js?id=83d2b662603978fa3f1c:1
(anonymous) @ app.js?id=be62b8fed3ae4954fef2:1
I3G/.e.$emit @ vendor.js?id=83d2b662603978fa3f1c:1
update @ app.js?id=be62b8fed3ae4954fef2:1
click @ app.js?id=be62b8fed3ae4954fef2:1
t @ vendor.js?id=83d2b662603978fa3f1c:1
Pr.t._withTask.a._withTask @ vendor.js?id=83d2b662603978fa3f1c:1
o @ app.js?id=be62b8fed3ae4954fef2:1
vendor.js?id=83d2b662603978fa3f1c:1 Uncaught (in promise) Error: Request failed with status code 422
    at FtD3.e.exports (vendor.js?id=83d2b662603978fa3f1c:1)
    at e.exports (vendor.js?id=83d2b662603978fa3f1c:1)
    at XMLHttpRequest.h.(anonymous function) (https://media.gmodstore.com/assets/js/vendor.js?id=83d2b662603978fa3f1c:1:57737)
    at XMLHttpRequest.o (app.js?id=be62b8fed3ae4954fef2:1)
FtD3.e.exports @ vendor.js?id=83d2b662603978fa3f1c:1
e.exports @ vendor.js?id=83d2b662603978fa3f1c:1
h.(anonymous function) @ vendor.js?id=83d2b662603978fa3f1c:1
o @ app.js?id=be62b8fed3ae4954fef2:1
Promise.then (async)
(anonymous) @ app.js?id=be62b8fed3ae4954fef2:1
I3G/.e.$emit @ vendor.js?id=83d2b662603978fa3f1c:1
(anonymous) @ app.js?id=be62b8fed3ae4954fef2:1
I3G/.e.$emit @ vendor.js?id=83d2b662603978fa3f1c:1
update @ app.js?id=be62b8fed3ae4954fef2:1
click @ app.js?id=be62b8fed3ae4954fef2:1
t @ vendor.js?id=83d2b662603978fa3f1c:1
Pr.t._withTask.a._withTask @ vendor.js?id=83d2b662603978fa3f1c:1
o @ app.js?id=be62b8fed3ae4954fef2:1`

**Comment by Marcuzz** [comment]
Yeah, because it throws a 403. I just need to catch the error and display it really.

**Comment by Marcuzz** [comment]
Fixed
