### ISSUE TITLE
Message notification

### ISSUE THREAD

**Issue by 0wain** [gmodstore/gmodstore-issues#87]
Regardless of if you reply to a message or mark all messages as read, you still receive a red notification mark on your message notification box that won't go away.

Basically, message notifications won't go away.

**Comment by OwjoTheGreat** [comment]
It seems that if the user responds, the notification goes away. But then if you reply, the notification comes back and won't leave again.

**Comment by Marcuzz** [comment]
How weird, it clears the cache on all message participants, and also clears it on mark all as read...
