### ISSUE TITLE
Homepage "Back to top" button under-lapping.

### ISSUE THREAD

**Issue by OwjoTheGreat** [gmodstore/gmodstore-issues#88]
When scrolled to the bottom of the home page, the "Back to top" button is underlapped by the company registration information. Making it partially unclickable and creates overlapping text.

I'm using Chrome, just in case that was relevant.

**Comment by Threebow** [comment]
Also fucks up the page on mobile

**Comment by Marcuzz** [comment]
Fixed in next deployment
