### ISSUE TITLE
Jobs' application 403, 

### ISSUE THREAD

**Issue by IamOmni** [gmodstore/gmodstore-issues#97]
![image](https://user-images.githubusercontent.com/22639649/43588995-542f2694-96a0-11e8-86ed-fc9bc20cde80.png)
Clicking this gives me a 403

![image](https://user-images.githubusercontent.com/22639649/43589037-75aa128e-96a0-11e8-8466-bb1ea2237958.png)
Wrong stats and status (should be 2 applications)

**Comment by Marcuzz** [comment]
Jobs are not done yet

**Comment by Marcuzz** [comment]
403 fixed, stats will be fixed later when I finish jobs
